apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              chmod +x /scripts/wait-for-kafka.sh
              /scripts/wait-for-kafka.sh
          volumeMounts:
            - name: wait-for-volume
              mountPath: /scripts
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.6.5
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka-cluster-kafka-bootstrap.backend.svc.cluster.local:9092
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry

          readinessProbe:
            httpGet:
              path: /subjects
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /subjects
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

      volumes:
        - name: wait-for-volume
          configMap:
            name: wait-for-script
            defaultMode: 0755
