apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-pvc
  namespace: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default-storage
