apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-cluster
  namespace: backend
spec:
  image: asia-northeast1-docker.pkg.dev/market-streaming-prod/flink-microstructures-extractor/flink-microstructures-extractor:0.5.2 # {"$imagepolicy": "flux-system:flink-microstructures-extractor"}
  flinkVersion: v1_20
  serviceAccount: flink
  flinkConfiguration:
    # env.java.opts.taskmanager: >-
    #   -XX:+UseG1GC
    #   -XX:MaxGCPauseMillis=10
    #   -XX:InitiatingHeapOccupancyPercent=45
    #   -XX:+AlwaysPreTouch
    #   -Dscala.usejavacp=false
    #   -Dlog4j2.Script.enableLanguages=none
    #   -XX:G1NewSizePercent=25
    #   -XX:G1MaxNewSizePercent=50
    # env.java.opts.jobmanager: >-
    #   -XX:+UseG1GC
    #   -XX:MaxGCPauseMillis=50
    #   -XX:+AlwaysPreTouch
    #   -Dscala.usejavacp=false
    #   -Dlog4j2.Script.enableLanguages=none
    #   -XX:+UnlockExperimentalVMOptions
    #   -XX:+ExplicitGCInvokesConcurrent
    # --------------------------------------------------------------------
    # Metric reporter
    # --------------------------------------------------------------------
    metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    metrics.reporter.prom.port: "8082"
    metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporters: prom
    # --------------------------------------------------------------------
    # Fault-tolerance
    # --------------------------------------------------------------------
    restart-strategy.type: fixed-delay
    restart-strategy.fixed-delay.attempts: "3"
    restart-strategy.fixed-delay.delay: 5s
    cleanup-strategy.type: fixed-delay
    cleanup-strategy.fixed-delay.attempts: "3"
    cleanup-strategy.fixed-delay.delay: 5s
    # --------------------------------------------------------------------
    # State backend
    # --------------------------------------------------------------------
    state.backend.type: hashmap
    # --------------------------------------------------------------------
    # High availability
    # --------------------------------------------------------------------
    high-availability.type: kubernetes
    high-availability.storageDir: file:///flink-data/ha
    # --------------------------------------------------------------------
    # Execution
    # --------------------------------------------------------------------
    execution.runtime-mode: STREAMING
    execution.buffer-timeout.enabled: "true"
    execution.buffer-timeout.interval: 0ms
    # --------------------------------------------------------------------
    # Pipeline
    # --------------------------------------------------------------------
    pipeline.max-parallelism: "128"
    pipeline.auto-generate-uids: "false"
    # --------------------------------------------------------------------
    # Checkpointing (disabled)
    # --------------------------------------------------------------------
    execution.checkpointing.unaligned.enabled: "true"
    execution.checkpointing.aligned-checkpoint-timeout: 200ms
    execution.checkpointing.unaligned.forced: "false"
    execution.checkpointing.cleaner.parallel-mode: "true"
    execution.checkpointing.storage: filesystem
    execution.checkpointing.dir: file:///flink-data/checkpoints
    execution.checkpointing.savepoint-dir: file:///flink-data/savepoints
    execution.checkpointing.incremental: "true"
    execution.checkpointing.num-retained: "5"
    execution.checkpointing.tolerable-failed-checkpoints: "1"
    execution.checkpointing.externalized-checkpoint-retention: DELETE_ON_CANCELLATION
    execution.checkpointing.file-merging.max-space-amplification: "2"
    # execution.checkpointing.interval: 15s
    execution.checkpointing.max-concurrent-checkpoints: "1"
    execution.checkpointing.timeout: 15s
    execution.checkpointing.local-backup.enabled: "false"
    execution.checkpointing.mode: EXACTLY_ONCE
    execution.checkpointing.unaligned.max-subtasks-per-channel-state-file: "5"
    execution.checkpointing.snapshot-compression: "true"
    # --------------------------------------------------------------------
    # Pekko
    # --------------------------------------------------------------------
    pekko.framesize: "104857600b" # 100Mi
    # --------------------------------------------------------------------
    # Restauration / Recovery
    # --------------------------------------------------------------------
    execution.state-recovery.claim-mode: NO_CLAIM
    execution.state-recovery.from-local: "false"
    execution.state-recovery.ignore-unclaimed-state: "false"
    # --------------------------------------------------------------------
    # JobManager
    # --------------------------------------------------------------------
    jobstore.cache-size: "1048576"
    jobstore.max-capacity: "10"
    blob.storage.directory: file:///flink-data/blob-storage
    kubernetes.jobmanager.cpu.limit-factor: "1.5"
    # JVM non-Flink
    jobmanager.memory.process.size: "1248m"
    # --------------------------------------------------------------------
    # TaskManager
    # --------------------------------------------------------------------
    taskmanager.numberOfTaskSlots: "9"
    taskmanager.slot.timeout: 20s
    taskmanager.memory.process.size: "8096m"
    kubernetes.taskmanager.cpu.limit-factor: "1.5"
    taskmanager.memory.segment-size: 4kb
    # --------------------------------------------------------------------
    # Metrics
    # --------------------------------------------------------------------
    rest.flamegraph.enabled: "true"
    # state.backend.rocksdb.metrics.live-sst-files-size: "true"
    # state.backend.rocksdb.metrics.cur-size-all-mem-tables: "true"
  logConfiguration:
    "log4j-console.properties": |
      status = WARN
      name = Log4j2Config
      appenders = Console, Async
      # --------------------------------------------------------------------
      # Console
      # --------------------------------------------------------------------
      appender.Console.type = Console
      appender.Console.name = Console
      appender.Console.target = SYSTEM_OUT
      appender.Console.layout.type = PatternLayout
      appender.Console.layout.pattern = %d{ISO8601} %-5level [%X{flink-job-id}] [%X{symbol}] [%X{exchange}] - %msg%n
      # --------------------------------------------------------------------
      # Async
      # --------------------------------------------------------------------
      appender.Async.type = Async
      appender.Async.name = Async
      appender.Async.includeThreadContext = true
      appender.Async.appenderRef.type = AppenderRef
      appender.Async.appenderRef.ref = Console
      # --------------------------------------------------------------------
      # Root
      # --------------------------------------------------------------------
      rootLogger.level = INFO
      rootLogger.appenderRef.Async.ref = Async
  jobManager:
    resource:
      memory: "1248m"
      cpu: 1.5
    podTemplate:
      spec:
        securityContext:
          fsGroup: 999
        containers:
          - name: flink-main-container
            envFrom:
              - configMapRef:
                  name: config-flink-env
            volumeMounts:
              - name: flink-volume
                mountPath: /flink-data
                readOnly: false
              - name: kafka-config-volume
                mountPath: /opt/flink/kafka-config
                readOnly: true
              - name: monitor-config-volume
                mountPath: /opt/flink/monitor-config
                readOnly: true
              - name: pipeline-config-volume
                mountPath: /opt/flink/pipeline-config
                readOnly: true
        volumes:
          - name: flink-volume
            persistentVolumeClaim:
              claimName: flink-pvc
          - name: kafka-config-volume
            configMap:
              name: config-flink-kafka
          - name: pipeline-config-volume
            configMap:
              name: config-flink-pipeline
          - name: monitor-config-volume
            configMap:
              name: config-flink-monitor
  taskManager:
    resource:
      memory: "8096m"
      cpu: 8
    podTemplate:
      spec:
        securityContext:
          fsGroup: 999
        containers:
          - name: flink-main-container
            envFrom:
              - configMapRef:
                  name: config-flink-env
            volumeMounts:
              - name: kafka-config-volume
                mountPath: /opt/flink/kafka-config
                readOnly: true
              - name: monitor-config-volume
                mountPath: /opt/flink/monitor-config
                readOnly: true
              - name: pipeline-config-volume
                mountPath: /opt/flink/pipeline-config
                readOnly: true
        volumes:
          - name: kafka-config-volume
            configMap:
              name: config-flink-kafka
          - name: pipeline-config-volume
            configMap:
              name: config-flink-pipeline
          - name: monitor-config-volume
            configMap:
              name: config-flink-monitor
  job:
    jarURI: local:///opt/flink/usrlib/app.jar
    upgradeMode: stateless
    parallelism: 1 # Overriden with pipeline-config.yaml
