apiVersion: v1
kind: ConfigMap
metadata:
  name: config-flink-kafka
  namespace: backend
data:
  kafka-source.properties: |
    # General reliability / timeout
    fetch.min.bytes=1
    fetch.max.wait.ms=4
    session.timeout.ms=10000
    heartbeat.interval.ms=3000
    max.poll.interval.ms=15000
    # Fetch sizing
    max.partition.fetch.bytes=1000000
    fetch.max.bytes=2000000
    max.poll.records=3000
    # Socket buffer
    receive.buffer.bytes=1000000
  kafka-sink.properties: |
    # Guarantees and reliability
    acks=0
    # Buffering and batching
    linger.ms=4
    batch.size=10000
     buffer.memory=67108864 
    compression.type=none
    # Timeouts and responsiveness
    request.timeout.ms=1000
    connections.max.idle.ms=540000
    session.timeout.ms=10000
    max.block.ms=30000
    # Limits to control payloads
    max.request.size=1000000
