apiVersion: v1
kind: ConfigMap
metadata:
  name: config-flink-pipeline
  namespace: backend
data:
  flink-pipeline.properties: |
    parallelism.orderbook=3
    parallelism.metrics.extraction1=1
    parallelism.metrics.extraction2=1
    parallelism.metrics.extraction3=1
    parallelism.sink=2
