apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokio-binance-scraper
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tokio-binance-scraper
  template:
    metadata:
      labels:
        app: tokio-binance-scraper
    spec:
      containers:
        - name: tokio
          image: tokio-binance-scraper:0.5.0
          ports:
            - containerPort: 9000
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: config-tokio-binance-scraper
          volumeMounts:
            - name: kafka-config-volume
              mountPath: /app/resources
              readOnly: true
          resources:
            requests:
              cpu: "1"
              memory: 500Mi
            limits:
              cpu: "1.5"
              memory: 1Gi
      volumes:
        - name: kafka-config-volume
          configMap:
            name: config-tokio-kafka
