apiVersion: v1
kind: ConfigMap
metadata:
  name: config-node-binance-scraper
  namespace: backend
data:
  KAFKA_CLIENT_ID: "binance-scraper"
  KAFKA_BROKER_HOST: "kafka-cluster-kafka-bootstrap.backend.svc.cluster.local:9092"
  SCHEMA_REGISTRY_URL: "http://schema-registry-cluster-ip.backend.svc.cluster.local:8081"
  CONFIG_ENABLE_SCRAPING: "true"
  DISABLE_APP_ADDRESS_LISTENING: "false"
  HOSTNAME: "0.0.0.0"
  PORT: "3000"
  BINANCE_WS_STREAMS: "bnbbtc@depth@100ms/btcusdt@depth@100ms"
  BINANCE_WS_URL: "stream.binance.com:9443/stream?streams="
  # BINANCE_WS_STREAMS: "bnbbtc@depth@100ms/btcusdt@depth@100ms/ethusdt@depth@100ms/ltcusdt@depth@100ms/xrpusdt@depth@100ms"
