apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tokio-symbols
  namespace: backend
data:
  symbols-config.yaml: |
    symbols:
      - ETHUSDT
      - BTCUSDT
      - FLOKIUSDT
      - XRPUSDT
      - DOGEUSDT
      - SOLUSDT
      - ZECUSDT
      - BNBUSDT
      - BONKUSDT
      - BREVUSDT
      - ZKPUSDT
      - SUIUSDT
      - ETHUSDC
      - BTCUSDC
      - SHIBUSDT
      - USDCUSDT
      - GUNUSDT
      - VIRTUALUSDT
      - PEPEUSDT
      - BNBUSDC
      - BABYUSDT
      - SPKUSDT
      - PENGUUSDT
      - ADAUSDT
      - GIGGLEUSDT
      - HBARUSDT
      - LTCUSDT
      - TAOUSDT
      - FETUSDT
      - NEIROUSDT
      - SUIUSDC
      - BCHUSDT
      - CRVUSDT
      - XRPUSDC
      - WLDUSDT
      - NEARUSDT
      - UNIUSDT
      - TIAUSDT
      - XPLUSDT
      - WLFIUSDT
      - AAVEUSDT
      - ZENUSDT
      - BTCUSD1
      - PUMPUSDT
      - RENDERUSDT
      - TRUMPUSDT
      - XLMUSDT
      - SOLUSDC
      - CVCUSDT
      - USD1USDT
      - KAITOUSDT
      - STRAXUSDT
      - ENAUSDT
      - AIXBTUSDT
      - AVAXUSDT
      - TRXUSDT
      - FILUSDT
      - ASTERUSDT
      - PEPEUSDC
      - DOGEUSDC
      - TONUSDT
      - LINKUSDT
      - FFUSDT
      - ANIMEUSDT
      - ICPUSDT
      - DOTUSDT
      - ETHUSD1
      - WIFUSDT
      - HBARUSDC
      - POLUSDT
      - CHZUSDT
      - ACHUSDT
      - ADAUSDC
      - ONDOUSDT
      - LDOUSDT
      - ETCUSDT
      - SYRUPUSDT
      - WLFIUSD1
      - ZKUSDT
      - STXUSDT
      - INJUSDT
      - ETHBTC
      - KITEUSDT
      - PROMUSDT
      - USDTBRL
      - DASHUSDT
      - TAOUSDC
      - ORDIUSDT
      - PARTIUSDT
      - SEIUSDT
      - RLCUSDT
      - APTUSDT
      - LUNCUSDT
      - BOMEUSDT
      - 2ZUSDT
      - MUBARAKUSDT
      - AMPUSDT
      - CUSDT
      - BTCEUR
      - PAXGUSDT
      - ARBUSDT
      - PNUTUSDT
      - HUMAUSDT
      - OPUSDT
      - GLMUSDT
      - PENDLEUSDT
      - ATOMUSDT
      - SAHARAUSDT
      - JASMYUSDT
      - SUSDT
      - FUNUSDT
      - LINKUSDC
      - ETHEUR
      - ETHFIUSDT
      - APEUSDT
      - GUSDT
      - YBUSDT
      - EIGENUSDT
      - ENAUSDC
      - LAYERUSDT
      - BNBBTC
      - GRTUSDT
      - ARKMUSDT
      - SOMIUSDT
      - SSVUSDT
      - A2ZUSDT
      - MBLUSDT
      - LTCUSDC
      - BBUSDT
      - RAYUSDT
      - BTCBRL
      - RESOLVUSDT
      - TUSDT
      - LINEAUSDT
      - RSRUSDT
      - SXPUSDT
      - KMNOUSDT
      - BCHUSDC
      - BARDUSDT
      - ZROUSDT
      - SNXUSDT
      - CAKEUSDT
      - ZBTUSDT
      - QNTUSDT
      - BIOUSDT
      - XRPBTC
      - ARUSDT
      - PROVEUSDT
      - TURBOUSDT
      - XTZUSDT
      - FLOKIUSDC
      - VETUSDT
      - PEOPLEUSDT
      - SANDUSDT
      - BIGTIMEUSDT
      - AVNTUSDT
      - XAIUSDT
      - TWTUSDT
      - CELRUSDT
      - IOTAUSDT
      - SHELLUSDT
      - ALGOUSDT
      - ZECBTC
      - STRKUSDT
      - NEOUSDT
      - DYDXUSDT
      - DOLOUSDT
      - DOGEUSD1
      - PLUMEUSDT
      - GMTUSDT
      - ERAUSDT
      - MORPHOUSDT
      - WALUSDT
      - ENSOUSDT
      - SKYUSDT
      - METUSDT
      - AVAXUSDC
      - MAGICUSDT
      - OMUSDT
      - QIUSDT
      - JUPUSDT
      - LUNAUSDT
      - MOVRUSDT
      - FETUSDC
      - CFXUSDT
      - ENSUSDT
      - TRXUSDC
      - 0GUSDT
      - ALLOUSDT
      - TFUELUSDT
      - BANANAUSDT
      - MMTUSDT
      - MEUSDT
      - AUSDT
      - TRBUSDT
      - SAPIENUSDT
      - TRUMPUSDC
      - TREEUSDT
      - NEARUSDC
      - DOGSUSDT
      - EPICUSDT
      - LPTUSDT
      - TUTUSDT
      - ALGOUSDC
      - TNSRUSDT
      - SUNUSDT
      - ALPINEUSDT
      - EDENUSDT
      - HOMEUSDT
      - ETHBRL
      - MEMEUSDT
      - DIAUSDT
      - SOLUSD1
      - WCTUSDT
      - XLMUSDC
      - COTIUSDT
      - DOTUSDC
      - API3USDT
      - BATUSDT
      - DUSKUSDT
      - SUSHIUSDT
      - IMXUSDT
      - AUDIOUSDT
      - EULUSDT
      - VANAUSDT
      - HMSTRUSDT
      - FLOWUSDT
      - CGPTUSDT
      - YGGUSDT
      - AXSUSDT
      - CKBUSDT
      - OPENUSDT
      - ADAUSD1
      - SOLVUSDT
      - JTOUSDT
      - ICXUSDT
      - DEGOUSDT
      - MAVUSDT
      - CTSIUSDT
      - RUNEUSDT
      - KAVAUSDT
      - GPSUSDT
      - MANAUSDT
      - CVXUSDT
      - COOKIEUSDT
      - INJUSDC
      - PYTHUSDT
      - SHIBUSDC
      - JSTUSDT
      - DYMUSDT
      - SYNUSDT
      - SFPUSDT
      - DEXEUSDT
      - USUALUSDT
      - METISUSDT
      - ILVUSDT
      - NOMUSDT
      - EGLDUSDT
      - SUPERUSDT
      - NMRUSDT
      - TOWNSUSDT
      - GMXUSDT
      - LISTAUSDT
      - IOUSDT
      - NEWTUSDT
      - PORTALUSDT
      - MANTAUSDT
      - WIFUSDC
      - BERAUSDT
      - KSMUSDT
      - SKLUSDT
      - KERNELUSDT
      - NOTUSDT
      - VTHOUSDT
      - COMPUSDT
      - WOOUSDT
      - PHAUSDT
      - SOPHUSDT
      - BLURUSDT
      - IDUSDT
      - AEVOUSDT
      - INITUSDT
      - DATAUSDT
      - QTUMUSDT
      - ALICEUSDT
      - CATIUSDT
      - ANKRUSDT
      - CHRUSDT
      - MIRAUSDT
      - CELOUSDT
      - CETUSUSDT
      - FLUXUSDT
      - WBTCUSDT
      - BMTUSDT
      - ATOMUSDC
      - PIXELUSDT
      - KAIAUSDT
      - DCRUSDT
      - EDUUSDT
      - WUSDT
      - TRXBTC
      - POLYXUSDT
      - REZUSDT
      - NFPUSDT
      - HFTUSDT
      - USTCUSDT
      - PUNDIXUSDT
      - AGLDUSDT
      - NILUSDT
      - ZKCUSDT
      - FIDAUSDT
      - BCHBTC
      - ASTRUSDT
      - TLMUSDT
      - DUSDT
      - ROSEUSDT
      - XECUSDT
      - FUSDT
      - BICOUSDT
      - YFIUSDT
      - TURTLEUSDT
      - LINKBTC
      - STGUSDT
      - QKCUSDT
      - XRPUSD1
      - SIGNUSDT
      - AUCTIONUSDT
      - HEIUSDT
      - ONEUSDT
      - MINAUSDT
      - WINUSDT
      - THETAUSDT
      - MASKUSDT
      - OSMOUSDT
      - ACXUSDT
      - MOVEUSDT
      - PYRUSDT
      - SXTUSDT
      - CYBERUSDT
      - LSKUSDT
      - LUMIAUSDT
      - IOSTUSDT
      - ZILUSDT
      - ADXUSDT
      - XRPETH
      - UMAUSDT
      - MTLUSDT
      - USDTDAI
      - PONDUSDT
      - GASUSDT
      - FTTUSDT
      - SLPUSDT
      - LAUSDT
      - RPLUSDT
      - NXPCUSDT
      - WBTCBTC
      - RUNEUSDC
      - SUSDC
      - RVNUSDT
      - RONINUSDT
      - FORTHUSDT
      - DGBUSDT
      - IOTXUSDT
      - DODOUSDT
      - NTRNUSDT
      - COWUSDT
      - TONUSDC
      - GLMRUSDT
      - SCRUSDT
      - ENJUSDT
      - KNCUSDT
      - C98USDT
      - 1INCHUSDT
      - ZRXUSDT
      - QUICKUSDT
      - LRCUSDT
      - HYPERUSDT
      - STORJUSDT
      - SCRTUSDT
      - HAEDALUSDT
      - BANDUSDT
      - RDNTUSDT
      - JUPUSDC
      - AVAUSDT
      - HOLOUSDT
      - OPUSDC
      - AVAXBTC
      - LQTYUSDT
      - HIGHUSDT
      - XNOUSDT
      - NKNUSDT
      - ONDOUSDC
      - DENTUSDT
      - DOGEBTC
      - OXTUSDT
      - GNSUSDT
      - ONTUSDT
      - STOUSDT
      - OGNUSDT
      - TRUUSDT
      - VANRYUSDT
      - REQUSDT
      - TRXETH
      - SYSUSDT
      - ORCAUSDT
      - WANUSDT
      - ATAUSDT
      - DOTBTC
      - ARPAUSDT
      - AWEUSDT
      - XLMBTC
      - STXBTC
      - PAXGBTC
      - LTCBTC
      - ADABTC
      - RLCBTC
      - AAVEBTC
      - TUSDUSDT
      - NEARBTC
      - ICPBTC
      - FLUXUSDC
      - HBARBTC
      - LDOUSDC
      - GTCUSDT
      - USDEUSDT
      - FETBTC
      - LTCETH
      - AUSDC
      - ETHDAI
      - DASHBTC
      - ETCBTC
      - APEUSDC
      - ONTBTC
      - ETCUSDC
      - SHIBDOGE
      - EGLDBTC
      - BTCDAI
      - CHZBTC
      - LUNCUSDC
      - ALGOBTC
      - XTZBTC
      - KNCBTC
      - ARBTC
      - ATOMBTC
      - XLMETH
      - USDPUSDT
      - NEOBTC
      - GMTUSDC
      - SNXBTC
      - RUNEBTC
      - SCRTBTC
      - ATOMETH
      - VETBTC
      - ZILETH
      - LUNAUSDC
      - INJBTC
      - ETCETH
      - IOTXETH
      - IOTABTC
      - DASHETH
      - ABTC
      - OGNBTC
      - WANBTC
      - VETETH
      - AVABTC
      - MANAETH
      - COTIBTC
      - WINTRX
