apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-cluster
  namespace: backend
spec:
  image: flink-microstructures-extractor:2.3.1
  flinkVersion: v1_20
  serviceAccount: flink

  flinkConfiguration:
    execution.checkpointing.dir: file:///flink-data/checkpoints
    execution.savepoints.dir: file:///flink-data/savepoints

  logConfiguration: {}

  jobManager:
    resource:
      memory: "0.5gb"
      cpu: 0.5
  taskManager:
    resource:
      memory: "2gb"
      cpu: 4

  podTemplate:
    spec:
      volumes:
        - name: flink-conf
          configMap:
            name: flink-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: log4j
          configMap:
            name: config-flink-log4j
        - name: kafka-config-volume
          configMap:
            name: config-flink-kafka
        - name: pipeline-config-volume
          configMap:
            name: config-flink-pipeline
        - name: flink-volume
          hostPath:
            path: /tmp/flink
            type: Directory

      containers:
        - name: flink-main-container
          envFrom:
            - configMapRef:
                name: config-flink-env
          volumeMounts:
            - name: flink-conf
              mountPath: /opt/flink/conf
              readOnly: true
            - name: log4j
              mountPath: /opt/flink/conf/log4j-console.properties
              subPath: log4j-console.properties
              readOnly: true
            - name: kafka-config-volume
              mountPath: /opt/flink/kafka-config
              readOnly: true
            - name: pipeline-config-volume
              mountPath: /opt/flink/pipeline-config
              readOnly: true
            - name: flink-volume
              mountPath: /flink-data

  job:
    jarURI: local:///opt/flink/usrlib/app.jar
    upgradeMode: last-state
    state: running
    parallelism: 1
