apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-cluster
  namespace: backend
spec:
  image: flink-microstructures-extractor:2.3.1
  flinkVersion: v1_20
  serviceAccount: flink
  flinkConfiguration:
    state.checkpoints.dir: file:///flink-data/checkpoints
    state.savepoints.dir: file:///flink-data/savepoints
    high-availability: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    high-availability.storageDir: file:///flink-data/ha
    taskmanager.numberOfTaskSlots: "1"
    metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    metrics.reporter.prom.port: "8082"
    metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporters: prom
    env.java.opts.jobmanager: "-Dscala.usejavacp=false -Dlog4j2.Script.enableLanguages=none"
    env.java.opts.taskmanager: "-Dscala.usejavacp=false -Dlog4j2.Script.enableLanguages=none"
    state.backend.type: rocksdb
    execution.buffer-timeout.interval: 0ms

  logConfiguration:
    "log4j-console.properties": |
      status = WARN
      name = Log4j2Config
      appenders = Console, Async

      appender.Console.type = Console
      appender.Console.name = Console
      appender.Console.target = SYSTEM_OUT
      appender.Console.layout.type = PatternLayout
      appender.Console.layout.pattern = %d{ISO8601} %-5level [%X{flink-job-id}] [%X{key}] - %msg%n

      appender.Async.type = Async
      appender.Async.name = Async
      appender.Async.includeThreadContext = true
      appender.Async.appenderRef.type = AppenderRef
      appender.Async.appenderRef.ref = Console

      rootLogger.level = INFO
      rootLogger.appenderRef.Async.ref = Async

  jobManager:
    resource:
      memory: "1gb"
      cpu: 0.5
  taskManager:
    resource:
      memory: "2gb"
      cpu: 4

  podTemplate:
    spec:
      securityContext:
        fsGroup: 999
      volumes:
        - name: kafka-config-volume
          configMap:
            name: config-flink-kafka
        - name: pipeline-config-volume
          configMap:
            name: config-flink-pipeline
        - name: flink-volume
          persistentVolumeClaim:
            claimName: flink-state

      containers:
        - name: flink-main-container
          envFrom:
            - configMapRef:
                name: config-flink-env
          volumeMounts:
            - name: kafka-config-volume
              mountPath: /opt/flink/kafka-config
              readOnly: true
            - name: pipeline-config-volume
              mountPath: /opt/flink/pipeline-config
              readOnly: true
            - name: flink-volume
              mountPath: /flink-data

  job:
    jarURI: local:///opt/flink/usrlib/app.jar
    upgradeMode: last-state
    state: running
    parallelism: 1
