apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-cluster
  namespace: backend
spec:
  image: flink-microstructures-extractor:2.3.1
  flinkVersion: v1_20
  serviceAccount: flink
  flinkConfiguration:
    # --------------------------------------------------------------------
    # Metric reporter
    # --------------------------------------------------------------------
    metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    metrics.reporter.prom.port: "8082"
    metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporters: prom
    # --------------------------------------------------------------------
    # JVM options
    # --------------------------------------------------------------------
    env.java.opts.jobmanager: "-Dscala.usejavacp=false -Dlog4j2.Script.enableLanguages=none"
    env.java.opts.taskmanager: "-Dscala.usejavacp=false -Dlog4j2.Script.enableLanguages=none"
    # --------------------------------------------------------------------
    # Fault-tolerance
    # --------------------------------------------------------------------
    restart-strategy.type: fixed-delay
    restart-strategy.fixed-delay.attempts: "3"
    restart-strategy.fixed-delay.delay: 5s
    cleanup-strategy.type: fixed-delay
    cleanup-strategy.fixed-delay.attempts: "3"
    cleanup-strategy.fixed-delay.delay: 5s
    # --------------------------------------------------------------------
    # State backend
    # --------------------------------------------------------------------
    state.backend.type: rocksdb
    state.backend.rocksdb.checkpoint.transfer.thread.num: "4"
    state.backend.rocksdb.block.cache-size: 16mb
    state.backend.rocksdb.writebuffer.count: "2"
    state.backend.rocksdb.writebuffer.size: 64mb
    state.backend.rocksdb.compression.per.level: SNAPPY_COMPRESSION
    state.backend.rocksdb.use-bloom-filter: "false"
    # --------------------------------------------------------------------
    # High availability
    # --------------------------------------------------------------------
    high-availability.type: kubernetes
    high-availability.storageDir: file:///flink-data/ha
    # --------------------------------------------------------------------
    # Execution
    # --------------------------------------------------------------------
    execution.runtime-mode: STREAMING
    execution.buffer-timeout.enabled: "true"
    execution.buffer-timeout.interval: 0ms
    # --------------------------------------------------------------------
    # Pipeline
    # --------------------------------------------------------------------
    pipeline.max-parallelism: "64"
    pipeline.auto-generate-uids: "false"
    # --------------------------------------------------------------------
    # Checkpointing
    # --------------------------------------------------------------------
    execution.checkpointing.unaligned.enabled: "true"
    execution.checkpointing.aligned-checkpoint-timeout: 30s
    execution.checkpointing.unaligned.forced: "false"
    execution.checkpointing.cleaner.parallel-mode: "true"
    execution.checkpointing.storage: filesystem
    execution.checkpointing.dir: file:///flink-data/checkpoints
    execution.checkpointing.savepoint-dir: file:///flink-data/savepoints
    execution.checkpointing.incremental: "true"
    execution.checkpointing.num-retained: "5"
    execution.checkpointing.externalized-checkpoint-retention: DELETE_ON_CANCELLATION
    execution.checkpointing.file-merging.max-space-amplification: "2"
    execution.checkpointing.interval: 10m
    execution.checkpointing.max-concurrent-checkpoints: "1"
    execution.checkpointing.timeout: 9m
    execution.checkpointing.local-backup.enabled: "false"
    execution.checkpointing.mode: EXACTLY_ONCE
    execution.checkpointing.unaligned.max-subtasks-per-channel-state-file: "5"
    execution.checkpointing.snapshot-compression: "true"
    # --------------------------------------------------------------------
    # State Changelog
    # --------------------------------------------------------------------
    state.changelog.enabled: "true"
    state.changelog.periodic-materialize.enabled: "true"
    state.changelog.periodic-materialize.interval: 2min
    state.changelog.storage: memory
    # --------------------------------------------------------------------
    # Restauration / Recovery
    # --------------------------------------------------------------------
    execution.state-recovery.claim-mode: NO_CLAIM
    execution.state-recovery.from-local: "false"
    execution.state-recovery.ignore-unclaimed-state: "false"
    # --------------------------------------------------------------------
    # JobManager
    # --------------------------------------------------------------------
    jobstore.cache-size: "256000"
    jobstore.max-capacity: "1"
    blob.storage.directory: file://flink-data/blob-storage
    jobmanager.memory.flink.size: 512m
    jobmanager.memory.process.size: 716m
    # --------------------------------------------------------------------
    # TaskManager
    # --------------------------------------------------------------------
    taskmanager.numberOfTaskSlots: "5"
    taskmanager.slot.timeout: 30s
    taskmanager.memory.process.size: 1024m
    taskmanager.memory.flink.size: 716m

  logConfiguration:
    "log4j-console.properties": |
      status = WARN
      name = Log4j2Config
      appenders = Console, Async
      # --------------------------------------------------------------------
      # Console
      # --------------------------------------------------------------------
      appender.Console.type = Console
      appender.Console.name = Console
      appender.Console.target = SYSTEM_OUT
      appender.Console.layout.type = PatternLayout
      appender.Console.layout.pattern = %d{ISO8601} %-5level [%X{flink-job-id}] [%X{key}] - %msg%n
      # --------------------------------------------------------------------
      # Async
      # --------------------------------------------------------------------
      appender.Async.type = Async
      appender.Async.name = Async
      appender.Async.includeThreadContext = true
      appender.Async.appenderRef.type = AppenderRef
      appender.Async.appenderRef.ref = Console
      # --------------------------------------------------------------------
      # Root
      # --------------------------------------------------------------------
      rootLogger.level = INFO
      rootLogger.appenderRef.Async.ref = Async

  jobManager:
    resource:
      memory: "1024m"
      cpu: 0.5
  taskManager:
    resource:
      memory: "1536m"
      cpu: 1

  podTemplate:
    spec:
      securityContext:
        fsGroup: 999
      volumes:
        - name: kafka-config-volume
          configMap:
            name: config-flink-kafka
        - name: pipeline-config-volume
          configMap:
            name: config-flink-pipeline
        - name: flink-volume
          persistentVolumeClaim:
            claimName: flink-state

      containers:
        - name: flink-main-container
          envFrom:
            - configMapRef:
                name: config-flink-env
          volumeMounts:
            - name: kafka-config-volume
              mountPath: /opt/flink/kafka-config
              readOnly: true
            - name: pipeline-config-volume
              mountPath: /opt/flink/pipeline-config
              readOnly: true
            - name: flink-volume
              mountPath: /flink-data

  job:
    jarURI: local:///opt/flink/usrlib/app.jar
    upgradeMode: last-state
    state: running
    parallelism: 1
