apiVersion: v1
kind: ConfigMap
metadata:
  name: config-flink-log4j
  namespace: backend
data:
  log4j-console.properties: |
    status = WARN
    name = Log4j2Config
    appenders = Console, Async

    appender.Console.type = Console
    appender.Console.name = Console
    appender.Console.target = SYSTEM_OUT
    appender.Console.layout.type = PatternLayout
    appender.Console.layout.pattern = %d{ISO8601} %-5level [%X{flink-job-id}] [%X{key}] - %msg%n

    appender.Async.type = Async
    appender.Async.name = Async
    appender.Async.includeThreadContext = true
    appender.Async.appenderRef.type = AppenderRef
    appender.Async.appenderRef.ref = Console

    rootLogger.level = INFO
    rootLogger.appenderRef.Async.ref = Async
