apiVersion: v1
kind: Service
metadata:
  name: flink-metrics
  namespace: backend
  labels:
    app: flink-metrics
spec:
  selector:
    app: flink-cluster
  ports:
    - name: tcp-prometheus
      protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP