apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-broker-controller-pool
  namespace: backend
  labels:
    strimzi.io/cluster: kafka-cluster
    app: kafka-pool
spec:
  replicas: 3
  storage:
    type: persistent-claim
    size: 40Gi
    class: kafka-storage
    kraftMetadata: shared
  roles:
    - controller
    - broker
  resources:
    requests:
      memory: 9Gi
      cpu: "5"
    limits:
      memory: 9Gi
      cpu: "6"
  jvmOptions:
    -Xms: "2048m"
    -Xmx: "2048m"
    # -XX:
    #   UseG1GC: "true"
    #   MaxGCPauseMillis: "10"
    #   InitiatingHeapOccupancyPercent: "30"
    #   ExplicitGCInvokesConcurrent: "true"
    #   UnlockExperimentalVMOptions: "true"
    #   AlwaysPreTouch: "true"
    #   G1NewSizePercent: "25"
    #   G1MaxNewSizePercent: "50"
