apiVersion: druid.apache.org/v1alpha1
kind: Druid
metadata:
  name: cluster
  namespace: backend
spec:
  image: docker.io/charlescol01/druid-protobuf-kafka:druid-34.0.0-custom-0.0.2
  startScript: /druid.sh
  serviceAccount: druid-sa
  podLabels:
    app: druid-cluster
  podAnnotations:
    app: druid-cluster
  readinessProbe:
    httpGet:
      path: /status/health
      port: 8088
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
    fsGroupChangePolicy: Always
  commonConfigMountPath: "/opt/druid/conf/druid/cluster/_common"
  jvm.options: |-
    -server
    -XX:MaxDirectMemorySize=2g
    -Duser.timezone=UTC
    -Dfile.encoding=UTF-8
    -Dlog4j.debug
    -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
    -Djava.io.tmpdir=/tmp
  log4j.config: |-
    <?xml version="1.0" encoding="UTF-8" ?>
    <Configuration status="WARN">
        <Appenders>
            <Console name="Console" target="SYSTEM_OUT">
                <PatternLayout pattern="%d{ISO8601} %p [%t] %c - %m%n"/>
            </Console>
        </Appenders>
        <Loggers>
            <Root level="info">
                <AppenderRef ref="Console"/>
            </Root>
        </Loggers>
    </Configuration>
  common.runtime.properties: |
    druid.zk.service.enabled=false
    druid.discovery.type=k8s
    druid.discovery.k8s.clusterIdentifier=cluster

    druid.serverview.type=http
    druid.coordinator.loadqueuepeon.type=http
    druid.indexer.runner.type=httpRemote

    # Monitoring
    druid.emitter=prometheus
    druid.emitter.prometheus.strategy=exporter
    druid.emitter.prometheus.port=9000
    druid.emitter.prometheus.endpoint=/metrics
    druid.emitter.prometheus.namespace=druid
    druid.emitter.prometheus.addHostAsLabel=true
    druid.emitter.prometheus.addServiceAsLabel=true

    # Metadata Store
    druid.metadata.storage.type=postgresql
    druid.metadata.storage.connector.connectURI=jdbc:postgresql://druid-postgres.backend.svc.cluster.local:5432/druid
    druid.metadata.storage.connector.user=druid
    druid.metadata.storage.connector.createTables=true
    druid.metadata.storage.connector.password={ "type": "environment", "variable": "DRUID_METADATA_PG_PASSWORD" }

    # Deep Storage
    druid.storage.type=google
    druid.google.bucket=druid-storage-market-streaming-prod
    druid.google.prefix=druid/segments
    druid.google.maxListingLength=1024

    # Extensions
    druid.extensions.loadList=["druid-histogram", \
    "druid-datasketches", \
    "druid-lookups-cached-global", \
    "postgresql-metadata-storage", \
    "druid-multi-stage-query", \
    "druid-kafka-indexing-service", \
    "druid-protobuf-extensions", \
    "druid-kubernetes-extensions", \
    "prometheus-emitter", \
    "druid-google-extensions"]

    # Service discovery
    druid.selectors.indexing.serviceName=druid/overlord
    druid.selectors.coordinator.serviceName=druid/coordinator

    druid.indexer.logs.type=file
    druid.indexer.logs.directory=/druid/data/indexing-logs
    druid.lookup.enableLookupSyncOnStartup=false

  volumeMounts:
    - name: gcp-credentials
      mountPath: /var/secrets/google
      readOnly: true

  volumes:
    - name: gcp-credentials
      secret:
        secretName: gcs-sa-key
  env:
    - name: DRUID_METADATA_PG_PASSWORD
      valueFrom:
        secretKeyRef:
          name: druid-pg-auth
          key: password
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /var/secrets/google/gcp-key.json

    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP

    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace

  nodes:
    brokers:
      kind: Deployment
      nodeType: "broker"
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/query/broker"
      replicas: 1
      runtime.properties: |
        druid.host=${env:POD_IP}
        druid.service=druid/broker
        # HTTP server threads
        druid.broker.http.numConnections=5
        druid.server.http.numThreads=10
        # Processing threads and buffers
        druid.processing.buffer.sizeBytes=1
        druid.processing.numMergeBuffers=1
        druid.processing.numThreads=1
        druid.sql.enable=true
      extra.jvm.options: |-
        -Xms512M

    coordinators:
      nodeType: "coordinator"
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/master/coordinator-overlord"
      replicas: 1
      volumeClaimTemplates:
        - metadata:
            name: druid-task-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
            storageClassName: standard
        - metadata:
            name: druid-logs
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
            storageClassName: standard

      volumeMounts:
        - name: druid-task-data
          mountPath: /druid/data/persistent/task
        - name: druid-logs
          mountPath: /druid/data/indexing-logs
      runtime.properties: |
        druid.host=${env:POD_IP}
        druid.service=druid/coordinator
        druid.indexer.task.baseDir=/druid/data
        druid.indexer.logs.type=file
        druid.indexer.logs.directory=/druid/data/indexing-logs

        # HTTP server threads
        druid.coordinator.startDelay=PT30S
        druid.coordinator.period=PT30S

        # Configure this coordinator to also run as Overlord
        druid.coordinator.asOverlord.enabled=true
        druid.coordinator.asOverlord.overlordService=druid/overlord
        druid.indexer.queue.startDelay=PT30S
      extra.jvm.options: |-
        -Xmx512M
        -Xms512M

    historicals:
      nodeType: "historical"
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/data/historical"
      replicas: 1
      volumeClaimTemplates:
        - metadata:
            name: segment-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: standard
      volumeMounts:
        - name: segment-volume
          mountPath: /druid/data
      runtime.properties: |
        druid.host=${env:POD_IP}
        druid.service=druid/historical
        druid.server.http.numThreads=5
        druid.processing.buffer.sizeBytes=536870912
        druid.processing.numMergeBuffers=1
        druid.processing.numThreads=1

        # Segment storage
        druid.segmentCache.locations=[{\"path\":\"/druid/data/segments\",\"maxSize\":10737418240}]
        druid.server.maxSize=10737418240
      extra.jvm.options: |-
        -Xmx512M
        -Xms512M

    routers:
      nodeType: "router"
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/query/router"
      replicas: 1
      services:
        - spec:
            type: ClusterIP
            clusterIP: None
      runtime.properties: |
        druid.host=${env:POD_IP}
        druid.service=druid/router

        # HTTP proxy
        druid.router.http.numConnections=15
        druid.router.http.readTimeout=PT5M
        druid.router.http.numMaxThreads=20
        druid.server.http.numThreads=12

        # Service discovery
        druid.router.defaultBrokerServiceName=druid/broker
        druid.router.coordinatorServiceName=druid/coordinator

        # Management proxy to coordinator / overlord: required for unified web console.
        druid.router.managementProxy.enabled=true
        druid.router.sql.enable=true
      extra.jvm.options: |-
        -Xmx512M
        -Xms512M

    indexers:
      nodeType: "indexer"
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/data/indexer"
      replicas: 2
      resources:
        requests:
          cpu: "4"
          memory: "5Gi"
        limits:
          cpu: "6"
          memory: "7Gi"
      volumeClaimTemplates:
        - metadata:
            name: druid-task-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
            storageClassName: standard
        - metadata:
            name: druid-logs
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
            storageClassName: standard
        - metadata:
            name: segment-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
            storageClassName: standard
      volumeMounts:
        - name: druid-task-data
          mountPath: /druid/data/persistent/task
        - name: druid-logs
          mountPath: /druid/data/indexing-logs
        - name: segment-volume
          mountPath: /druid/data/segments
      volumes:
        - name: task-tmp
          emptyDir: {}
      runtime.properties: |
        druid.host=${env:POD_IP}
        druid.service=druid/indexer
        druid.worker.capacity=2
        druid.worker.globalIngestionHeapLimitBytes=3758096384
        druid.indexer.task.baseDir=/druid/data
        druid.indexer.logs.type=file
        druid.indexer.logs.directory=/druid/data/indexing-logs
        druid.segmentCache.locations=[{"path":"/druid/data/segments","maxSize":10737418240}]
        druid.server.maxSize=5368709120
      extra.jvm.options: |-
        -Xms4g
        -Xmx4608m
