apiVersion: v1
kind: Secret
metadata:
  name: druid-postgres-secret
  namespace: backend
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: druid-postgres
  namespace: backend
spec:
  serviceName: druid-postgres-hl
  replicas: 1 # TODO HA with Patroni/Bitnami/managed services
  selector:
    matchLabels:
      app: druid-postgres
  template:
    metadata:
      labels:
        app: druid-postgres
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: druid
            - name: POSTGRES_USER
              value: druid
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: druid-pg-auth
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_INITDB_ARGS
              value: --data-checksums
          readinessProbe:
            exec:
              command:
                [
                  "sh",
                  "-lc",
                  'pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432',
                ]
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
                [
                  "sh",
                  "-lc",
                  'pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432',
                ]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      terminationGracePeriodSeconds: 60
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: default-storage
        resources:
          requests:
            storage: 10Gi
