apiVersion: v1
kind: Service
metadata:
  name: druid-postgres-hl
  namespace: backend
  labels:
    app: druid-postgres
spec:
  clusterIP: None # headless
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: druid-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: druid-postgres
  namespace: backend
  labels:
    app: druid-postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: druid-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-router
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: druid
    component: router
    druid_cr: cluster
  ports:
    - name: http
      port: 8088
      targetPort: 8088
