apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-druid
  namespace: backend
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: druid-cluster
  namespaceSelector:
    matchNames:
      - backend
  endpoints:
    - port: tcp-prometheus
      interval: 10s
      scrapeTimeout: 5s
      path: ""
      scheme: http
  jobLabel: prometheus-druid
  targetLabels:
    - prometheus-druid
