apiVersion: v1
kind: Service
metadata:
  name: tokio-binance-scraper-metrics
  namespace: backend
  labels:
    app: tokio-binance-scraper-metrics
    exchange: binance
spec:
  selector:
    app: tokio-binance-scraper
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: tcp-prometheus
  type: ClusterIP
