apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: backend
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 3.9.0
    image: docker.io/charlescol01/kafka-docker-custom:kafka-3.9.0-custom-0.0.1
    metadataVersion: 3.9-IV0
    listeners:
      # - name: debug # Only for debugging purposes
      #   port: 9095
      #   type: internal
      #   tls: false
      - name: internal # For inter-cluster communication
        port: 9092
        type: internal
        tls: false # TODO: Change to true
    template:
      kafkaContainer:
        env:
          - name: JAVA_TOOL_OPTIONS
            value: >
              -javaagent:/opt/pyroscope/pyroscope.jar
              -XX:+UnlockDiagnosticVMOptions
              -XX:+DebugNonSafepoints
          - name: PYROSCOPE_SERVER_ADDRESS
            value: http://pyroscope.backend.svc.cluster.local:4040
          - name: PYROSCOPE_PROFILING_INTERVAL
            value: "20ms"
          - name: PYROSCOPE_LOG_LEVEL
            value: "info"
    config:
      compression.type: "uncompressed"
      controller.listener.names: "CONTROLLER"
      # --------------------------------------------------------------------
      # I/O and network
      # --------------------------------------------------------------------
      log.dir: "/kafka-data/logs"
      queued.max.requests: 500
      socket.receive.buffer.bytes: 104857600
      socket.request.max.bytes: 104857600 # 100MB
      socket.send.buffer.bytes: -1
      broker.heartbeat.interval.ms: 5000
      # --------------------------------------------------------------------
      # # Threads
      # --------------------------------------------------------------------
      background.threads: 8 # log cleanup, metrics reporting, and various internal housekeeping operations.
      num.io.threads: 8
      num.network.threads: 6
      num.recovery.threads.per.data.dir: 1 # Log recovery at startup or  surwhen a broker crashes
      num.replica.alter.log.dirs.threads: 1 # Handles replica movement between log directories (e.g., during log directory rebalancing).
      num.replica.fetchers: 5
      group.coordinator.threads: 1 # Consumer group coordination, including heartbeats, offset commits, and group rebalancing.
      # --------------------------------------------------------------------
      # # Replication
      # --------------------------------------------------------------------
      replica.fetch.min.bytes: 1
      replica.fetch.max.bytes: 8388608 # 8MiB
      replica.fetch.wait.max.ms: 3
      replica.high.watermark.checkpoint.interval.ms: 5000
      replica.lag.time.max.ms: 5000
      replica.socket.receive.buffer.bytes: 1048576 # 1MiB
      replica.socket.timeout.ms: 30000
      default.replication.factor: 2
      min.insync.replicas: 1
      # --------------------------------------------------------------------
      # # Kraft
      # --------------------------------------------------------------------
      controller.quorum.election.backoff.max.ms: 5000
      controller.quorum.election.timeout.ms: 1000
      controller.quorum.fetch.timeout.ms: 10000
      metadata.log.max.record.bytes.between.snapshots: 20971520
      metadata.log.max.snapshot.interval.ms: 20971520 # 30 minutes
      metadata.log.segment.bytes: 1073741824 # 32MB
      metadata.max.retention.bytes: 104857600
      metadata.max.retention.ms: 604800000 # 30 minutes
      # --------------------------------------------------------------------
      # # Topics / ISR / Monitoring
      # --------------------------------------------------------------------
      auto.create.topics.enable: false
      delete.topic.enable: true
      eligible.leader.replicas.enable: true
      auto.leader.rebalance.enable: false
      unclean.leader.election.enable: false
      metrics.recording.level: "INFO"
      # --------------------------------------------------------------------
      # # Offsets (__consumer_offsets)
      # --------------------------------------------------------------------
      offsets.commit.timeout.ms: 1000
      offsets.retention.check.interval.ms: 600000
      offsets.retention.minutes: 10080
      offsets.topic.num.partitions: 5
      offsets.topic.replication.factor: 2
      offsets.topic.segment.bytes: 1048576
      # --------------------------------------------------------------------
      # # Log / Storage
      # --------------------------------------------------------------------
      log.segment.bytes: 1073741824
      log.roll.ms: 3600000 # 60 minutes
      log.roll.jitter.ms: 2700000 # 45 minutes
      log.segment.delete.delay.ms: 180000 # 3 minutes
      log.retention.check.interval.ms: 120000 # 2 minute
      log.flush.offset.checkpoint.interval.ms: 30000
      log.flush.interval.messages: 9223372036854775807
      log.flush.scheduler.interval.ms: 9223372036854775807

    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml

  entityOperator:
    topicOperator: {}
    userOperator: {}
