apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: binance-session-job
  namespace: backend
spec:
  deploymentName: flink-cluster

  flinkConfiguration:
    pipeline.name: "binance-session-job"

  job:
    jarURI: http://flink-jar-server.backend.svc.cluster.local/app.jar
    entryClass: "com.marketanalysis.microstructuresextractor.ExtractMicrostructures"
    args:
      - "--job-conf-dir"
      - "/opt/flink/job-configs/binance"
    parallelism: 1
    upgradeMode: stateless
    state: running
