apiVersion: v1
kind: ConfigMap
metadata:
  name: config-flink-job-kucoin
  namespace: backend
data:
  config.yaml: |
    KAFKA_TOPIC_EXCHANGE_DEPTH_UPDATE: "kucoin-depthUpdate-raw"
    KAFKA_TOPIC_EXCHANGE_MICROSTRUCTURE: "kucoin-microstructure-raw"
    KAFKA_TOPIC_EXCHANGE_DEPTH_SNAPSHOT: "kucoin-depthSnapshot-raw"
    KAFKA_BOOTSTRAP_SERVERS: "kafka-cluster-kafka-bootstrap.backend.svc.cluster.local:9092"
    SCHEMA_REGISTRY_URL: "http://schema-registry-cluster-ip.backend.svc.cluster.local:8081"
    EXCHANGE_NAME: "kucoin"
    JAVA_TOOL_OPTIONS: "--add-opens=java.base/java.util=ALL-UNNAMED"
    MAX_GAPS_BEFORE_SNAPSHOT: "2"
    MAX_SNAPSHOT_REQUESTS_IN_SYNC: "5"
    USE_CUSTOM_ORDERBOOK_SERIALIZER: "false"
    MAX_SNAPSHOT_REQUESTS_RETRY: "3"
    ORDER_BOOK_MIN_DEPTH_PERCENT: "35"
    ORDER_BOOK_SNAPSHOT_DEPTH: "1000"
    TIMEOUT_SNAPSHOT_REQUEST_SECONDS: "10"
    ENABLE_EXTRACTION_VERBOSE: "false"
    ENABLE_ORDERBOOK_VERBOSE: "true"
    TRACKED_SYMBOLS: ""
    SNAPSHOT_REQUEST_URL: "http://tokio-kucoin-middleware-http.backend.svc.cluster.local:3000/request/snapshot"
    MAX_BUFFER_LENGTH: "10000"
    MAX_BUFFER_CLEAR_COUNT: "3"
  flink-pipeline.yaml: |
    source:
      depthupdate:
        parallelism: 3
        sharing-group: "default"
      snapshot:
        parallelism: 1
        sharing-group: "default"
    orderbook:
      parallelism: 5
      sharing-group: "orderbook-group"
    metrics:
      extraction1:
        parallelism: 3
        sharing-group: "feature1"
      extraction2:
        parallelism: 3
        sharing-group: "feature2"
      extraction3:
        parallelism: 3
        sharing-group: "feature3"
    sink:
      parallelism: 4
      sharing-group: "sink-group"
  kafka-source.properties: |
    fetch.min.bytes=1
    fetch.max.wait.ms=4           
    max.partition.fetch.bytes=262144   
    client.id=kucoin-microstructure-source
    fetch.max.bytes=524288             
    max.poll.records=500
    receive.buffer.bytes=524288
  kafka-sink.properties: |
    acks=0
    linger.ms=4
    batch.size=10000
    buffer.memory=67108864 
    client.id=kucoin-microstructure-sink
    compression.type=none
    request.timeout.ms=1000
    connections.max.idle.ms=540000
    session.timeout.ms=10000
    max.block.ms=30000
    max.request.size=1000000
  monitoring-config.yaml: |
    symbols:
      - ETH-USDT
      - BTC-USDT
      - FLOKI-USDT
      - DASH-ETH
      - A-BTC
