apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/apps/flink
patchesStrategicMerge:
  - deployment.yaml
  - services.yaml
  - kafka-config.yaml
  - pipeline-config.yaml
  - env-config.yaml
  - flink-config.yaml
  - log4j-config.yaml
