apiVersion: v1
kind: ConfigMap
metadata:
  name: config-flink-monitor
  namespace: backend
data:
  monitor-conf.yaml: |
    symbols:
      - FLOKIUSDT
      - ETHUSDT
      - BTCFDUSD
      - BONKUSDT
      - BTCUSDT
      - SOLUSDT
      - ETHFDUSD
      - XRPUSDT
      - TSTUSDT
      - ENAUSDT
      - DOGEUSDT
      - BNBUSDT
      - SOLFDUSD
      - LTCUSDT
      - BNBFDUSD
      - PROVEUSDT
      - DOGEFDUSD
      - ETHUSDC
      - SUIUSDT
      - TOWNSUSDT
      - SPELLUSDT
      - PENGUUSDT
      - BCHUSDT
      - USDCUSDT
      - TREEUSDT
      - SHIBUSDT
      - HBARUSDT
      - XRPFDUSD
      - SUIUSDC
      - NEIROUSDT
      - ADAUSDT
      - CFXUSDT
      - SYRUPUSDT
      - CRVUSDT
      - XRPUSDC
      - PEPEUSDT
      - SPKUSDT
      - BTCUSDC
      - OMNIUSDT
      - UNIUSDT
      - OMUSDT
      - XLMUSDT
      - FDUSDUSDT
      - EPICUSDT
      - SPELLTRY
      - ONDOUSDT
      - VIRTUALUSDT
      - ASRUSDT
      - SEIUSDT
      - TOWNSTRY
