apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-state
  namespace: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
