apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kafka-kustomization.yaml
  - schema-registry-kustomization.yaml
  - prometheus-kustomization.yaml
  - flink-kustomization.yaml
  - binance-middleware-kustomization.yaml
  - scrapers-kustomization.yaml
  # - tokio-binance-mock-kustomization.yaml
  - druid-kustomization.yaml
