apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kafka-kustomization.yaml
  - schema-registry-kustomization.yaml
  - prometheus-kustomization.yaml
  - flink-kustomization.yaml
  - middleware-kustomization.yaml
  - scraper-kustomization.yaml
  # - tokio-binance-mock-kustomization.yaml
  - druid-kustomization.yaml
