apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-prometheus
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./binance/apps/prometheus
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: app-kafka
    - name: app-flink
    - name: app-binance-middleware
    - name: app-scrapers
