apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokio-exchange-middleware
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tokio-exchange-middleware
  template:
    metadata:
      labels:
        app: tokio-exchange-middleware
    spec:
      imagePullSecrets:
        - name: flux-gcp-key
      containers:
        - name: tokio
          mage: asia-northeast1-docker.pkg.dev/market-streaming-prod/tokio-exchange-middleware/tokio-exchange-middleware:0.1.1 # {"$imagepolicy": "flux-system:tokio-exchange-middleware"}
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 9000
              name: metrics
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: config-tokio-exchange-middleware
          volumeMounts:
            - name: kafka-config-volume
              mountPath: /app/resources/kafka
              readOnly: true
            - name: symbol-priority-volume
              mountPath: /app/resources/symbols
              readOnly: true
          resources:
            requests:
              cpu: "1"
              memory: 500Mi
            limits:
              cpu: "1"
              memory: 1Gi
      volumes:
        - name: kafka-config-volume
          configMap:
            name: config-exchange-middleware-kafka
        - name: symbol-priority-volume
          configMap:
            name: config-exchange-middleware-symbol-priority
