apiVersion: v1
kind: PersistentVolume
metadata:
  name: gce-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cluster-retain
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/market-streaming-prod/zones/asia-northeast1-b/disks/gce-pv-disk
    fsType: ext4
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gce-pvc
  namespace: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: gce-pv
  storageClassName: cluster-retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cluster-retain
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: pd-ssd
