apiVersion: v1
kind: Service
metadata:
  name: druid-postgres-hl
  namespace: backend
  labels:
    app: druid-postgres
spec:
  clusterIP: None # headless
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: druid-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: druid-postgres
  namespace: backend
  labels:
    app: druid-postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: druid-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: druid-broker-metrics
  namespace: backend
  labels:
    app: druid-cluster
spec:
  type: ClusterIP
  selector:
    app: druid
    component: broker
  ports:
    - name: tcp-prometheus
      protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: druid-router-metrics
  namespace: backend
  labels:
    app: druid-cluster
spec:
  type: ClusterIP
  selector:
    app: druid
    component: router
  ports:
    - name: tcp-prometheus
      protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: druid-coordinator-metrics
  namespace: backend
  labels:
    app: druid-cluster
spec:
  selector:
    app: druid
    component: coordinator
  type: ClusterIP
  ports:
    - name: tcp-prometheus
      protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: druid-historical-metrics
  namespace: backend
  labels:
    app: druid-cluster
spec:
  selector:
    app: druid
    component: historical
  type: ClusterIP
  ports:
    - name: tcp-prometheus
      protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: druid-indexer-metrics
  namespace: backend
  labels:
    app: druid-cluster
spec:
  selector:
    app: druid
    component: indexer
  type: ClusterIP
  ports:
    - name: tcp-prometheus
      protocol: TCP
      port: 9000
      targetPort: 9000
