apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tokio-kafka
  namespace: backend
data:
  kafka-sink-config.yaml: |
    acks: 1
    linger.ms: 2 
    batch.size: 180000
    compression.type: none
    retries: 1
    message.timeout.ms: 1000
    broker.address.family: v4
    statistics.interval.ms: 1000
    log_level: 6
