apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tokio-symbols
  namespace: backend
data:
  symbols-config.yaml: |
    symbols:
      - FLOKIUSDT
      - ETHUSDT
      - BTCFDUSD
      - BONKUSDT
      - BTCUSDT
      - SOLUSDT
      - ETHFDUSD
      - XRPUSDT
      - TSTUSDT
      - ENAUSDT
      - DOGEUSDT
      - BNBUSDT
      - SOLFDUSD
      - LTCUSDT
      - BNBFDUSD
      - PROVEUSDT
      - DOGEFDUSD
      - ETHUSDC
      - SUIUSDT
      - TOWNSUSDT
      - SPELLUSDT
      - PENGUUSDT
      - BCHUSDT
      - USDCUSDT
      - TREEUSDT
      - SHIBUSDT
      - HBARUSDT
      - XRPFDUSD
      - SUIUSDC
      - NEIROUSDT
      - ADAUSDT
      - CFXUSDT
      - SYRUPUSDT
      - CRVUSDT
      - XRPUSDC
      - PEPEUSDT
      - SPKUSDT
      - BTCUSDC
      - OMNIUSDT
      - UNIUSDT
      - OMUSDT
      - XLMUSDT
      - FDUSDUSDT
      - EPICUSDT
      - SPELLTRY
      - ONDOUSDT
      - VIRTUALUSDT
      - ASRUSDT
      - SEIUSDT
      - TOWNSTRY
      - ILVUSDT
      - FORMUSDT
      - AVAXUSDT
      - FUNUSDT
      - OMNITRY
      - TONUSDT
      - SOLUSDC
      - ENAUSDC
      - AAVEUSDT
      - WLDUSDT
      - PROVETRY
      - LINKUSDT
      - TRXUSDT
      - PROVEUSDC
      - MKRUSDT
      - LINKFDUSD
      - FDUSDUSDC
      - TOWNSUSDC
      - PENGUUSDC
      - DYDXUSDT
      - NEARUSDT
      - PEPEUSDC
      - ORDIUSDT
      - ETHFIUSDT
      - BIOUSDT
      - WIFUSDT
      - PENDLEUSDT
      - CAKEUSDT
      - PENGUTRY
      - USDTTRY
      - POLUSDT
      - DOGEUSDC
      - ETHBTC
      - REDUSDT
      - APTUSDT
      - ERAUSDT
      - ALGOUSDT
      - BNBUSDC
      - SUSDT
      - KERNELUSDT
      - ARBUSDT
      - SPKTRY
      - BOMEUSDT
      - HBARUSDC
      - HEIUSDT
      - LDOUSDT
      - INJUSDT
      - PNUTUSDT
      - ORCAUSDT
      - INITUSDT
      - GALAUSDT
      - MAVUSDT
      - THEUSDT
      - MUBARAKUSDT
      - MAGICUSDT
      - CFXUSDC
      - FXSUSDT
      - TURBOUSDT
      - ALTUSDT
      - ETCUSDT
      - PHBUSDT
      - TRBUSDT
      - BABYUSDT
      - A2ZUSDT
      - USDTBRL
      - NXPCUSDT
      - DOTUSDT
      - HUMAUSDT
      - SAHARAUSDT
      - ADAUSDC
      - SPKUSDC
      - TSTUSDC
      - KAITOUSDT
      - ZKUSDT
      - TSTTRY
      - BANANAS31USDT
      - ETHEUR
      - OPUSDT
      - OGUSDT
      - REZUSDT
      - DEXEUSDT
      - OMTRY
      - XTZUSDT
      - RSRUSDT
      - TAOUSDT
      - LTCUSDC
      - RUNEUSDT
      - RENDERUSDT
      - STOUSDT
      - ICPUSDT
      - TRUMPUSDT
      - BTCEUR
      - 1MBABYDOGEUSDT
      - FETUSDT
      - TIAUSDT
      - BIOTRY
      - BCHUSDC
      - COSUSDT
      - PIXELUSDT
      - APEUSDT
      - MEMEUSDT
      - JUPUSDT
      - SAGAUSDT
      - CVXUSDT
      - SYRUPUSDC
      - CUSDT
      - ENSUSDT
      - RAREUSDT
      - AIXBTUSDT
      - PYRUSDT
      - EURUSDT
      - KAVAUSDT
      - ZROUSDT
      - EURUSDC
      - EIGENUSDT
      - UMAUSDT
      - HYPERUSDT
      - FIOUSDT
      - CRVUSDC
      - ARKMUSDT
      - WCTUSDT
      - RPLUSDT
      - ENATRY
      - MBLUSDT
      - HFTUSDT
      - GASUSDT
      - GPSUSDT
      - ATOMUSDT
      - UNIUSDC
      - ETHTRY
      - BANANAS31USDC
      - SIGNUSDT
      - ETHJPY
      - PEOPLEUSDT
      - ALICEUSDT
      - QNTUSDT
      - AUSDT
      - PEPETRY
      - MEUSDT
      - JTOUSDT
      - FILUSDT
      - TREEUSDC
      - VETUSDT
      - CFXTRY
      - USDCTRY
      - BONKUSDC
      - HOOKUSDT
      - CKBUSDT
      - RAYUSDT
      - RESOLVUSDT
      - BROCCOLI714USDT
      - BONKTRY
      - USUALUSDT
      - OMUSDC
      - XLMUSDC
      - AMPUSDT
      - LINKUSDC
      - KDAUSDT
      - XRPEUR
      - COMPUSDT
      - DEGOUSDT
      - BEAMXUSDT
      - VICUSDT
      - WIFUSDC
      - IOUSDT
      - XRPTRY
      - STRKUSDT
      - ACHUSDT
      - NOTUSDT
      - BMTUSDT
      - RENDERUSDC
      - SOPHUSDT
      - SXTUSDT
      - SOLBTC
      - GUNUSDT
      - CETUSUSDT
      - AVAXUSDC
      - ONGUSDT
      - BBUSDT
      - ALGOUSDC
      - KAIAUSDT
      - NEWTUSDT
      - LPTUSDT
      - PROMUSDT
      - TREETRY
      - ACEUSDT
      - BANANAUSDT
      - LUNCUSDT
      - AWEUSDT
      - 1000SATSUSDT
      - BTCTRY
      - LAUSDT
