apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tokio-symbols
  namespace: backend
data:
  symbols-config.yaml: |
    symbols:
      - ETH-USDT
      - LTC-USDT
      - XRP-USDT
      - BCH-USDT
      - ADA-USDT
      - DOT-USDT
      - LINK-USDT
      - XLM-USDT
      - DOGE-USDT
      - SOL-USDT
      - MATIC-USDT
      - AVAX-USDT
      - SHIB-USDT
      - TRX-USDT
