apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tokio-symbols
  namespace: backend
data:
  symbols-config.yaml: |
    symbols:
      - ETH-USDT
      - SOL-USDT
      - XRP-USDT
      - XMR-USDT
      - BTC-USDC
      - LTC-USDT
      - ETH-USDC
      - FIGHT-USDT
      - SUI-USDT
      - USDC-USDT
      - ZEC-USDT
      - HYPE-USDT
      - BNB-USDT
      - SPACE-USD1
      - DOGE-USDT
      - PAXG-USDT
      - TON-USDT
      - ADA-USDT
      - TAO-USDT
      - ENSO-USDT
      - ROSE-USDT
      - PEPE-USDT
      - DASH-USDT
      - LINK-USDT
      - TRX-USDT
      - SOMI-USDT
      - NEAR-USDT
      - ZKC-USDT
      - USDT-USDC
      - IMU-USDT
      - GWEI-USDT
      - SOL-USDC
      - AVAX-USDT
      - LINEA-USDT
      - DMC-USDT
      - SPACE-USDT
      - SKR-USDT
      - FF-USDT
      - WLFI-USDT
      - SENT-USDT
      - PUMP-USDT
      - FOGO-USDT
      - PYBOBO-USDT
      - UNI-USDT
      - XRP-USDC
      - ACU-USDT
      - AVNT-USDT
      - XMR-USDC
      - SHIB-USDT
      - ATA-USDT
      - ZRO-USDT
      - USD1-USDT
      - ASTER-USDT
      - ONDO-USDT
      - PENGU-USDT
      - XLM-USDT
      - WCT-USDT
      - HBAR-USDT
      - LIT-USDT
      - WIF-USDT
      - KCS-USDT
      - XAUT-USDT
      - CC-USDT
      - TURTLE-USDT
      - DOT-USDT
      - XPL-USDT
      - ARB-USDT
      - KAS-USDT
      - TRUMP-USDT
      - APT-USDT
      - VENOM-USDT
      - KAIA-USDT
      - ENA-USDT
      - BCH-USDT
      - FET-USDT
      - TAIKO-USDT
      - ZBCN-USDT
      - AAVE-USDT
      - FARTCOIN-USDT
      - AXS-USDT
      - WMTX-USDT
      - AUCTION-USDT
      - ICP-USDT
      - USDT-EUR
      - CAI-USDT
      - USDT-BRL
      - BDX-USDT
      - FIL-USDT
      - US-USDT
      - LPT-USDT
      - STRK-USDT
      - RENDER-USDT
      - STO-USDT
      - BANANA-USDT
      - ATOM-USDT
      - BTR-USDT
      - STABLE-USDT
      - MIRA-USDT
      - FUN-USDT
      - SEI-USDT
      - POL-USDT
      - RAIN-USDT
      - LIGHT-USDT
      - VIRTUAL-USDT
      - ZBT-USDT
      - TIA-USDT
      - BB-USDT
      - MARS4-USDT
      - PYTH-USDT
      - ZEN-USDT
      - B2-USDT
      - ELSA-USDT
      - BONK-USDT
      - TRUTH-USDT
      - ULTIMA-USDT
      - WLD-USDT
      - CRV-USDT
      - ALKIMI-USDT
      - BLUAI-USDT
      - SPX-USDT
      - DUSK-USDT
      - PROVE-USDT
      - SAND-USDT
      - VSN-USDT
      - AKT-USDT
      - CHZ-USDT
      - FLOKI-USDT
      - ZK-USDT
      - XDC-USDT
      - NOM-USDT
      - 2Z-USDT
      - ATH-USDT
      - LTC-USDC
      - PLUME-USDT
      - OP-USDT
      - CLO-USDT
      - GPS-USDT
      - ALGO-USDT
      - MILADYCULT-USDT
      - LYN-USDT
      - MINA-USDT
      - ICNT-USDT
      - RESOLV-USDT
      - SYRUP-USDT
      - XPR-USDT
      - S-USDT
      - HFT-USDT
      - PENDLE-USDT
      - CRO-USDT
      - INJ-USDT
      - IP-USDT
      - TEL-USDT
      - EUL-USDT
      - VANA-USDT
      - NOT-USDT
      - JUP-USDT
      - PTB-USDT
      - BAN-USDT
      - IO-USDT
      - PRO-USDT
      - USELESS-USDT
      - ZIL-USDT
      - WET-USDT
      - W-USDT
      - USDC-EUR
      - AIXBT-USDT
      - TREE-USDT
      - VELO-USDT
      - DEEP-USDT
      - BNRENSHENG-USDT
      - USDT-DAI
      - XCN-USDT
      - SIGHT-USDT
      - RUNE-USDT
      - ADA-USDC
      - BULLA-USDT
      - QNT-USDT
      - JELLYJELLY-USDT
      - RAY-USDT
      - VET-USDT
      - AERO-USDT
      - CFX-USDT
      - AR-USDT
      - WOD-USDT
      - BMX-USDT
      - PRCL-USDT
      - WAL-USDT
      - ORDER-USDT
      - STBL-USDT
      - LDO-USDT
      - H-USDT
      - CPOOL-USDT
      - FOLKS-USDT
      - TRUST-USDT
      - GALAX-USDT
      - HOLO-USDT
      - AGLD-USDT
      - JASMY-USDT
      - ADI-USDT
      - MON-USDT
      - SCRT-USDT
      - BOB-USDT
      - HYPER-USDT
      - ETHFI-USDT
      - SQD-USDT
      - MOCA-USDT
      - ARKM-USDT
      - STG-USDT
      - DOGE-USDC
      - AGT-USDT
      - F-USDT
      - BRETT-USDT
      - SHELL-USDT
      - USDG-USDT
      - HIPPO-USDT
      - DRIFT-USDT
      - FLR-USDT
      - ANIME-USDT
      - INIT-USDT
      - SXT-USDT
      - IN-USDT
      - 0G-USDT
      - KAITO-USDT
      - NEWT-USDT
      - A-USDT
      - MOVE-USDT
      - OPEN-USDT
      - ORDI-USDT
      - SUPER-USDT
      - HANA-USDT
      - RSR-USDT
      - LAB-USDT
      - PIPE-USDT
      - APE-USDT
      - ZTC-USDT
      - TRB-USDT
      - MELANIA-USDT
      - STX-USDT
      - RATS-USDT
      - IRYS-USDT
      - BOME-USDT
      - ZKP-USDT
      - EIGEN-USDT
      - BERT-USDT
      - MOG-USDT
      - MET-USDT
      - POPCAT-USDT
      - BREV-USDT
      - BERA-USDT
      - NEO-USDT
      - GIGGLE-USDT
      - KITE-USDT
      - ETH-DAI
      - ASTR-USDT
      - TURBO-USDT
      - ZKJ-USDT
      - MBL-USDT
      - BTC-EUR
      - HAEDAL-USDT
      - KGEN-USDT
      - GRIFFAIN-USDT
      - ETC-USDT
      - MGO-USDT
      - SAHARA-USDT
      - ERA-USDT
      - XNY-USDT
      - NIGHT-USDT
      - MNT-USDT
      - BTC-USDG
      - IKA-USDT
      - Q-USDT
      - CAKE-USDT
      - SOPH-USDT
      - ZORA-USDT
      - NAKA-USDT
      - UNA-USDT
      - EWT-USDT
      - MAPO-USDT
      - CVX-USDT
      - COQ-USDT
      - NMR-USDT
      - SKY-USDT
      - LUNC-USDT
      - SPK-USDT
      - DN-USDT
      - NEIROCTO-USDT
      - TOKEN-USDT
      - HAIO-USDT
      - RWA-USDT
      - UAI-USDT
      - YGG-USDT
      - VR-USDT
      - CHEQ-USDT
      - ETN-USDT
      - PAAL-USDT
      - LYX-USDT
      - CKB-USDT
      - MANA-USDT
      - RVV-USDT
      - ANOME-USDT
      - BIO-USDT
      - SSV-USDT
      - A2Z-USDT
      - BAS-USDT
      - DOGS-USDT
      - SOLV-USDT
      - CSPR-USDT
      - MERL-USDT
      - FTT-USDT
      - G3-USDT
      - KNC-USDT
      - COTI-USDT
      - MYRO-USDT
      - XR-USDT
      - NATIX-USDT
      - HSK-USDT
      - B-USD1
      - VOOI-USDT
      - LL-USDT
      - WAXL-USDT
      - BEST-USDT
      - UB-USDT
      - TRAC-USDT
      - METIS-USDT
      - PNUT-USDT
      - XPIN-USDT
      - CYBER-USDT
      - THETA-USDT
      - ARTY-USDT
      - PROPS-USDT
      - CYS-USDT
      - XTZ-USDT
      - TOWER-USDT
      - ART-USDT
      - FLOCK-USDT
      - G-USDT
      - OM-USDT
      - ZEREBRO-USDT
      - BNB-USDC
      - DODO-USDT
      - CLANKER-USDT
      - SKL-USDT
      - DOT-USDC
      - EMYC-USDT
      - HLS-USDT
      - GOMINING-USDT
      - LAT-USDT
      - LUNA-USDT
      - ETH-EUR
      - SHR-USDT
      - NPC-USDT
      - REACT-USDT
      - COLS-USDT
      - U2U-USDT
      - FLUX-USDT
      - TROLL-USDT
      - SOL-USD1
      - PZP-USDT
      - SOON-USDT
      - CXT-USDT
      - READY-USDT
      - HNT-USDT
      - AITECH-USDT
      - OBT-USDT
      - ETH-USD1
      - AIOZ-USDT
      - IAG-USDT
      - VANRY-USDT
      - DYDX-USDT
      - PEAQ-USDT
      - ELIZAOS-USDT
      - PORTAL-USDT
      - AVAAI-USDT
      - XMN-USDT
      - TOSHI-USDT
      - REZ-USDT
      - XEM-USDT
      - HMSTR-USDT
      - BAT-USDT
      - VINU-USDT
      - ES-USDT
      - SUPRA-USDT
      - BMT-USDT
      - ENJ-USDT
      - WAVES-USDT
      - GUN-USDT
      - ORCA-USDT
      - BTC-USD1
      - D-USDT
      - ALU-USDT
      - PLAI-USDT
      - VFY-USDT
      - DAG-USDT
      - LINK-USDC
      - WAN-USDT
      - NTRN-USDT
      - SAPIEN-USDT
      - BTC-BRL
      - EGLD-USDT
      - PUBLIC-USDT
      - JST-USDT
      - KAS-USDC
      - KIMA-USDT
      - BNC-USDT
      - ZETA-USDT
      - RIO-USDT
      - ANLOG-USDT
      - MANTA-USDT
      - APR-USDT
      - PLAY-USDT
      - ZND-USDT
      - ACH-USDT
      - MV-USDT
      - HYPE-USDC
      - DATA-USDT
      - XDB-USDT
      - ALLO-USDT
      - VOLT-USDT
      - TWT-USDT
      - HUMA-USDT
      - SWARMS-USDT
      - DIGI-USDT
      - SKEY-USDT
      - SFP-USDT
      - USUAL-USDT
      - MLK-USDT
      - XYO-USDT
      - PUFFER-USDT
      - AEVO-USDT
      - ENS-USDT
      - PHA-USDT
      - PERP-USDT
      - MOODENG-USDT
      - ELP-USDT
      - BCHSV-USDT
      - VINE-USDT
      - BLAST-USDT
      - MUBARAK-USDT
      - CARV-USDT
      - ORAI-USDT
      - UDS-USDT
      - KERNEL-USDT
      - SWFTC-USDT
      - VSYS-USDT
      - JTO-USDT
      - KOMA-USDT
      - SIDUS-USDT
      - XRD-USDT
      - WLFI-USD1
      - TRX-USDC
      - CROSS-USDT
      - COMP-USDT
      - MOVR-USDT
      - ROAM-USDT
      - SUI-USDC
      - ARCSOL-USDT
      - IMX-USDT
      - ROOBEE-USDT
      - HPOS10I-USDT
      - VVV-USDT
      - RECALL-USDT
      - BIGTIME-USDT
      - PLANCK-USDT
      - XCH-USDT
      - ONE-USDT
      - ANYONE-USDT
      - TRUF-USDT
      - STRAX-USDT
      - IOTA-USDT
      - MAVIA-USDT
      - ELA-USDT
      - DCR-USDT
      - PROMPT-USDT
      - BCH-USDC
      - YZY-USDT
      - WIN-USDT
      - XTAG-USDT
      - CWEB-USDT
      - XCAD-USDT
      - PIN-USDT
      - LA-USDT
      - HEART-USDT
      - XU3O8-USDT
      - ARPA-USDT
      - ADX-USDC
      - API3-USDT
      - URANUS-USDT
      - MANYU-USDT
      - ADX-USDT
      - NYM-USDT
      - SOUL-USDT
      - SUT-USDT
      - HAI-USDT
      - FET-USDC
      - KMNO-USDT
      - ARIA-USDT
      - TRADE-USDT
      - SEED-USDT
      - YFI-USDT
