apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tokio-symbols
  namespace: backend
data:
  symbols-config.yaml: |
    symbols:
      - ETH-USDT
      - SOL-USDT
      - XRP-USDT
      - XMR-USDT
      - BTC-USDC
      - LTC-USDT
      - ETH-USDC
      - FIGHT-USDT
      - SUI-USDT
      - USDC-USDT
      - ZEC-USDT
      - HYPE-USDT
      - BNB-USDT
      - SPACE-USD1
      - DOGE-USDT
      - PAXG-USDT
      - TON-USDT
      - ADA-USDT
      - PEPE-USDT
      - ENSO-USDT
      - TAO-USDT
      - ROSE-USDT
      - LINK-USDT
      - DASH-USDT
      - SOMI-USDT
      - TRX-USDT
      - NEAR-USDT
      - ZKC-USDT
      - USDT-USDC
      - IMU-USDT
      - GWEI-USDT
      - SOL-USDC
      - AVAX-USDT
      - LINEA-USDT
      - DMC-USDT
      - SPACE-USDT
      - SKR-USDT
      - FF-USDT
      - WLFI-USDT
      - SENT-USDT
      - PUMP-USDT
      - UNI-USDT
      - PYBOBO-USDT
      - FOGO-USDT
      - ACU-USDT
      - XRP-USDC
      - AVNT-USDT
      - CC-USDT
      - XMR-USDC
