apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: grafana-cert
  namespace: backend
spec:
  domains:
    - grafana.charlescolella.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: backend
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "grafana-cert"
    kubernetes.io/ingress.global-static-ip-name: "grafana-global-ip"
spec:
  rules:
    - host: grafana.charlescolella.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-grafana
                port:
                  number: 80
