apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - helm-strimzi.yaml
  - sync-repo.yaml
  - helm-flink.yaml
  - helm-prometheus.yaml
