apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokio-kucoin-scraper
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tokio-kucoin-scraper
  template:
    metadata:
      labels:
        app: tokio-kucoin-scraper
    spec:
      initContainers:
        - name: wait-for-schema-registry
          image: busybox:1.36
          command: ["sh", "-c", "/scripts/wait-for-schema-registry.sh"]
          volumeMounts:
            - name: wait-for-volume
              mountPath: /scripts
      imagePullSecrets:
        - name: flux-gcp-key
      containers:
        - name: tokio
          image: asia-northeast1-docker.pkg.dev/market-streaming-prod/msv-tokio-kucoin-scraper/msv-tokio-kucoin-scraper:0.1.1 # {"$imagepolicy": "flux-system:msv-tokio-kucoin-scraper"}
          ports:
            - containerPort: 9000
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: config-tokio-kucoin-scraper
          volumeMounts:
            - name: kafka-config-volume
              mountPath: /app/resources/kafka
              readOnly: true
            - name: tokio-symbols-volume
              mountPath: /app/resources/symbols
              readOnly: true
          resources:
            requests:
              cpu: "2"
              memory: 500Mi
            limits:
              cpu: "4"
              memory: 1Gi
      volumes:
        - name: kafka-config-volume
          configMap:
            name: config-tokio-kafka
        - name: tokio-symbols-volume
          configMap:
            name: config-tokio-symbols
        - name: wait-for-volume
          configMap:
            name: wait-for-script
            defaultMode: 0755
