apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokio-kucoin-middleware
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tokio-kucoin-middleware
  template:
    metadata:
      labels:
        app: tokio-kucoin-middleware
    spec:
      imagePullSecrets:
        - name: flux-gcp-key
      containers:
        - name: tokio
          image: asia-northeast1-docker.pkg.dev/market-streaming-prod/tokio-kucoin-middleware/tokio-kucoin-middleware:0.1.5 # {"$imagepolicy": "flux-system:tokio-kucoin-middleware"}
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 9000
              name: metrics
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: config-tokio-kucoin-middleware
          env:
            - name: EXCHANGE_KUCOIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: kucoin-api-key
                  key: api-key
            - name: EXCHANGE_KUCOIN_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: kucoin-api-key
                  key: api-secret
            - name: EXCHANGE_KUCOIN_API_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: kucoin-api-key
                  key: api-passphrase
            - name: EXCHANGE_KUCOIN_API_KEY_VERSION
              valueFrom:
                secretKeyRef:
                  name: kucoin-api-key
                  key: api-key-version
          volumeMounts:
            - name: kafka-config-volume
              mountPath: /app/resources/kafka
              readOnly: true
            - name: symbol-priority-volume
              mountPath: /app/resources/symbols
              readOnly: true
          resources:
            requests:
              cpu: "0.5"
              memory: 500Mi
            limits:
              cpu: "0.5"
              memory: 1Gi
      volumes:
        - name: kafka-config-volume
          configMap:
            name: config-kucoin-middleware-kafka
        - name: symbol-priority-volume
          configMap:
            name: config-kucoin-middleware-symbol-priority
