apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kafka-monitors.yaml
  - flink-monitors.yaml
  - kucoin-middleware-monitors.yaml
  - binance-middleware-monitors.yaml
  - druid-monitors.yaml
  - binance-scraper-monitors.yaml
  - kucoin-scraper-monitors.yaml
