apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tokio-symbols
  namespace: backend
data:
  symbols-config.yaml: |
    symbols:
      - SHELLTRY
      - IDTRY
      - ROSETRY
      - BCHFDUSD
      - SLPTRY
      - NEARTRY
      - API3TRY
      - ENABTC
      - BMTUSDC
      - MORPHOTRY
      - BERATRY
      - STXBTC
      - ACXUSDC
      - AUSDC
      - COSTRY
      - SOLVTRY
      - ATUSDC
      - BANANATRY
      - TNSRUSDC
      - RENDERBRL
      - COWUSDC
      - AVAXEUR
      - SUIBRL
      - KITEUSDC
      - ALGOTRY
      - NEOUSDC
      - WIFBTC
      - ZROTRY
      - WLDBTC
      - MANTATRY
      - CKBUSDC
      - SUNTRY
      - INITUSDC
      - TONBTC
      - AITRY
      - FORMUSDC
      - ATOMFDUSD
      - OPENTRY
      - CATITRY
      - YBUSDC
      - SUIBNB
      - RESOLVTRY
      - XRPIDR
      - MANATRY
      - ETHDAI
      - ARTRY
      - ZENBTC
      - CAKETRY
      - LAYERUSDC
      - PLUMEUSDC
      - NFPTRY
      - LUNCUSDC
      - ARBBTC
      - ETCBTC
      - JUPFDUSD
      - APTBTC
      - NEARFDUSD
      - TURTLEUSDC
      - OPENFDUSD
      - SAGABTC
      - XUSDUSDT
      - PEOPLETRY
      - ENSOUSDC
      - SCRTRY
      - ERATRY
      - BANKUSDC
      - EDENTRY
      - ORCAUSDC
      - HYPERUSDC
      - TURTLETRY
      - SEIJPY
      - ETCUSDC
      - QTUMTRY
      - ETHIDR
      - 1MBABYDOGETRY
      - POLFDUSD
      - ARBETH
      - TWTTRY
      - ARDRBTC
      - AEVOUSDC
      - AUCTIONUSDC
      - RONINFDUSD
      - DOGEIDR
      - CYBERBTC
      - BTCARS
      - TOWNSUSDC
      - SEIFDUSD
      - XVGTRY
      - AXSUSDC
      - KNCBTC
      - LRCTRY
      - SXPBTC
      - TAOFDUSD
      - NOMTRY
      - BANANAUSDC
      - FUNUSDC
      - LPTBTC
      - YGGUSDC
      - LTCBRL
      - DODOTRY
      - CGPTUSDC
      - STEEMETH
      - TIABTC
      - OPFDUSD
      - TKOIDR
      - ROSEUSDC
      - PHATRY
      - AAVEFDUSD
      - RPLUSDC
      - ATMTRY
      - CRVBTC
      - ATOMBTC
      - OSMOUSDC
      - 1INCHUSDC
      - ATOMTRY
      - TRXFDUSD
      - ARBFDUSD
      - ASTRBTC
      - DENTTRY
      - RVNTRY
      - CKBTRY
      - DTRY
      - ARPATRY
      - ATRY
      - ONTBTC
      - STOTRY
      - SUPERTRY
      - NOTFDUSD
      - SNXBTC
      - SFDUSD
      - VETEUR
      - ICPEUR
      - UNIETH
      - PIXELUSDC
      - TRXBNB
      - SHIBDOGE
      - HUMATRY
      - APTFDUSD
      - ENJTRY
      - NOMUSDC
      - BNBARS
      - KAIAUSDC
      - DASHBTC
      - GPSUSDC
      - USDPUSDT
      - STGBTC
      - LAZIOTRY
      - ENSTRY
      - REZUSDC
      - GRTUSDC
      - MOVETRY
      - STXFDUSD
      - BONKFDUSD
      - AUCTIONBTC
      - ACXTRY
      - ZILTRY
      - XTZBTC
      - QNTBTC
      - BATBTC
      - TUSDC
      - MIRAUSDC
      - IDEXUSDC
      - SHIBBRL
      - ENABRL
      - LATRY
      - HEITRY
      - BTCDAI
      - PHBTRY
      - SAHARATRY
      - XVGUSDC
      - ORCATRY
      - PSGTRY
      - LPTUSDC
      - BARDUSDC
      - MEFDUSD
      - THETATRY
      - DOLOUSDC
      - IOBNB
      - SUIIDR
      - PORTOTRY
      - WBTCETH
      - BCHEUR
      - ONTUSDC
      - OGNTRY
      - HBARBNB
      - IMXUSDC
      - SAHARAUSDC
      - BIGTIMEUSDC
      - TONFDUSD
      - HOLOTRY
      - WLDFDUSD
      - LINKBNB
      - ZROBTC
      - WIFFDUSD
      - GASTRY
      - CELOTRY
      - ETCTRY
      - MAVUSDC
      - HIVEUSDC
      - ALGOBTC
      - COOKIEUSDC
      - DYDXFDUSD
      - NEARJPY
      - APTETH
      - RUNEETH
      - CATIUSDC
      - TWTUSDC
      - WINEUR
      - YBFDUSD
      - FLOKIFDUSD
      - ARBTC
      - BBBTC
      - CITYTRY
      - HOLOUSDC
      - NEWTTRY
      - SXTTRY
      - REDBTC
      - BCHJPY
      - AXSBTC
      - 1000CHEEMSUSDC
      - RDNTTRY
      - BNBIDR
      - SKLUSDC
      - ACMTRY
      - GMTUSDC
      - NEWTUSDC
      - SHELLUSDC
      - DOTETH
      - SIGNTRY
      - ANKRTRY
      - GRTEUR
      - ORDIFDUSD
      - ETCFDUSD
      - INJBTC
      - ADABNB
      - VANATRY
      - ZROFDUSD
      - WCTTRY
      - CAKEBTC
      - 1000CATUSDC
      - LAUSDC
      - XLMFDUSD
      - BTCTUSD
      - RUNEBTC
      - AXSTRY
      - API3USDC
      - CTKBNB
      - BARDTRY
      - DYMUSDC
      - METUSDC
      - NXPCTRY
      - METISTRY
      - LISTAUSDC
      - POLBTC
      - CTKBTC
      - SYNUSDC
      - MITOUSDC
      - EGLDBTC
      - COMPUSDC
      - YGGBTC
      - NTRNTRY
      - RLCBTC
      - TRUMPBRL
      - STEEMUSDC
      - QTUMUSDC
      - XECTRY
      - BLURUSDC
      - BTCUAH
      - MIRATRY
      - MTLBTC
      - AXLBTC
      - LINKBRL
      - AVAXBRL
      - SBTC
      - INITTRY
      - 2ZFDUSD
      - VIRTUALIDR
      - HBARFDUSD
      - FORTHBTC
      - NFPFDUSD
      - KAVABTC
      - EIGENFDUSD
      - RAYFDUSD
      - HIGHTRY
      - ATOMEUR
      - COTIUSDC
      - WIFEUR
      - XLMETH
      - CELOBTC
      - POLBRL
      - OGBTC
      - NILUSDC
      - HIVEBTC
      - POLEUR
      - ADAIDR
      - IOBTC
      - SCRTBTC
      - KSMTRY
      - ACTFDUSD
      - SAGAFDUSD
      - PIVXBTC
      - SUSHIBTC
      - DIABTC
      - TRUMPEUR
      - POLBNB
      - GPSBNB
      - ENJUSDC
      - VELODROMEUSDC
      - APEFDUSD
      - LSKBTC
      - ASTERIDR
      - SKYTRY
      - FLUXBTC
      - ALTFDUSD
      - ENABNB
      - NMRUSDC
      - ETHTUSD
      - BERABTC
      - SSVBTC
      - PYRBTC
      - ALTBNB
      - METTRY
      - AVAXBNB
      - DUSKBTC
      - NEARBNB
      - ICPETH
      - SEIBNB
      - ZBTBNB
      - PENDLEBTC
      - KAITOFDUSD
      - 1MBABYDOGEFDUSD
      - BCHBNB
      - SEIBTC
      - AWEBTC
      - CHZBTC
      - NEAREUR
      - XAIUSDC
      - MASKTRY
      - APTEUR
      - NEARBRL
      - EDENUSDC
      - SOLVUSDC
      - EGLDTRY
      - SUPERBTC
      - SCRBTC
      - STORJBTC
      - TRUMPFDUSD
      - OPEUR
      - GMXUSDC
      - NXPCUSDC
      - HAEDALUSDC
      - AEVOBTC
      - EULFDUSD
      - KERNELFDUSD
      - MASKUSDC
      - SCETH
      - BONKBRL
      - KERNELBNB
      - ATOMETH
      - MANABTC
      - SANDBTC
      - JSTBTC
      - LTCJPY
      - ICPFDUSD
      - ARBEUR
      - AEVOFDUSD
      - ZKBTC
      - PHABTC
      - AIBTC
      - PEOPLEFDUSD
      - SUSHITRY
      - CHESSUSDC
      - RVNUSDC
      - SANTOSBTC
      - BCHTRY
      - POLJPY
      - HEIUSDC
      - HEMIFDUSD
      - VANAUSDC
      - SOLARS
      - WFDUSD
      - IDBTC
      - ZBTFDUSD
      - APTJPY
      - HEIBTC
      - AUDIOBTC
      - XLMJPY
      - NEARETH
      - GASBTC
      - UMAUSDC
      - CFXBTC
      - ENSBTC
      - MOVRTRY
      - OPENBNB
      - TAOIDR
      - YFIBTC
      - HMSTRFDUSD
      - GALABRL
      - SEUR
      - PYTHFDUSD
      - ONGBTC
      - CTSIBTC
      - ARKMBTC
      - HOLOBNB
      - GALAEUR
      - LDOFDUSD
      - RENDERIDR
      - EIGENBTC
      - LUNAUSDC
      - MANTAFDUSD
      - KAITOBTC
      - LINEAFDUSD
      - NEOBTC
      - IMXBTC
      - FETBNB
      - YBBNB
      - GALAFDUSD
      - NEIROIDR
      - EGLDEUR
      - MAGICUSDC
      - PHBBTC
      - GRTFDUSD
      - SAGABNB
      - EGLDETH
      - CYBERFDUSD
      - IOTABTC
      - AGLDBTC
      - SUSHIUSDC
      - ARKMFDUSD
      - XTZTRY
      - HAEDALTRY
      - ZILETH
      - PORTALFDUSD
      - ORDIBTC
      - SBNB
      - PNUTFDUSD
      - WLDEUR
      - HOLOFDUSD
      - BNBTUSD
      - PNUTEUR
      - POLYXBTC
      - JTOFDUSD
      - VANAFDUSD
      - ETCETH
      - POLETH
      - OXTBTC
      - BBFDUSD
      - FILETH
      - BOMEFDUSD
      - LTCBNB
      - KSMBTC
      - ADXBTC
      - LSKUSDC
      - SOLTUSD
      - WIFIDR
      - WINTRX
      - ARBTUSD
      - DOTBNB
      - TRBBTC
      - EDENFDUSD
      - COMPBTC
      - BELBTC
      - API3BTC
      - RONINTRY
      - DOGSFDUSD
      - SOPHFDUSD
      - STRKFDUSD
      - GALAETH
      - HFTBTC
      - ENSOFDUSD
      - DOTBRL
      - APEBTC
      - ILVUSDC
      - WLFIEUR
      - SLPETH
      - SETH
      - SKYBTC
      - EULBNB
      - LAYERFDUSD
      - NEIROJPY
      - DYDXBTC
      - LDOBTC
      - GRTBTC
      - LAYERBTC
      - ARFDUSD
      - 0GBNB
      - NOMFDUSD
      - POLIDR
      - VETBTC
      - MANTABTC
      - ETHARS
      - SOLMXN
      - SOMIFDUSD
      - NMRTRY
      - XPLBNB
      - XVGETH
      - DASHETH
      - 1INCHBTC
      - CYBERETH
      - BANANABTC
      - PENDLEFDUSD
      - ABTC
      - WLDIDR
      - TONIDR
      - SKLBTC
      - JUVUSDC
      - TFUELBTC
      - NMRBTC
      - RAREBTC
      - MOVRBTC
      - UTKUSDC
      - BANDBTC
      - EGLDBNB
      - DOGSIDR
      - TIAIDR
      - MEUSDC
      - QTUMETH
      - HUMAFDUSD
      - LRCBTC
      - NEIROFDUSD
      - XNOBTC
      - LPTJPY
      - 0GFDUSD
      - PYTHBTC
      - RONINBTC
      - MIRABNB
      - TURTLEFDUSD
      - VETETH
      - AVAXIDR
      - ARBIDR
      - BANANABNB
      - ZILIDR
      - CAKEBNB
      - LINEABNB
      - FLOKIIDR
      - XVSBNB
      - IOFDUSD
      - PUNDIXUSDC
      - IOTXETH
      - DFUSDC
      - MANTAIDR
      - ATBNB
      - GMTEUR
      - OPBTC
      - IOTAETH
      - MINABTC
      - PNUTBTC
      - BERAFDUSD
      - TRUMPJPY
      - STOFDUSD
      - ICXBTC
      - ETHZAR
      - IOTXJPY
      - AVABTC
      - WCTBNB
      - GRTETH
      - ETHMXN
      - LABNB
      - HBARIDR
      - XRPMXN
      - MOVEBNB
      - JOEBTC
      - PARTIFDUSD
      - TURTLEBNB
      - BOMEIDR
      - BARDFDUSD
      - XRPTUSD
      - MAGICBTC
      - NFPBTC
      - SHELLBTC
      - CHZBNB
      - INJBNB
      - XPLFDUSD
      - MMTBNB
      - KITEBNB
      - ILVBTC
      - CYBERBNB
      - NTRNBNB
      - MEMEFDUSD
      - BANANAFDUSD
      - HEMIBNB
      - MANAETH
      - 1000SATSFDUSD
      - RLCETH
      - COTIBTC
      - ONDOIDR
      - DODOBTC
      - FIDABTC
      - REQBTC
      - WANBTC
      - PARTIBNB
      - OGNBTC
      - BIOBNB
      - SCRIDR
      - SYSBTC
      - XVSBTC
      - ROSEBTC
      - AXSETH
      - SSVETH
      - OPETH
      - MAVBTC
      - LRCETH
      - ZKCFDUSD
      - PLUMEBNB
      - 2ZBNB
      - MORPHOFDUSD
      - ALLOBNB
      - HOTETH
      - ALTBTC
      - BERABNB
      - SOMIBNB
      - SAPIENBNB
      - ARPABTC
      - PLUMEFDUSD
      - DOLOFDUSD
      - GLMRBTC
      - ETHFIFDUSD
      - MIRAFDUSD
      - EDENBNB
      - MORPHOBNB
