apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tokio-symbols
  namespace: backend
data:
  symbols-config.yaml: |
    symbols:
      - BTCUSDT
      - ETHUSDT
      - FLOKIUSDT
      - SOLUSDT
      - BTCFDUSD
      - XRPUSDT
      - DOGEUSDT
      - BNBUSDT
      - BONKUSDT
      - ETHFDUSD
      - ZECUSDT
      - SUIUSDT
      - BTCUSDC
      - ETHUSDC
      - USDCUSDT
      - ALLOUSDT
      - GIGGLEUSDT
      - SOLFDUSD
      - BANANAS31USDT
      - BNBUSDC
      - XPLUSDT
      - XRPFDUSD
      - BNBFDUSD
      - HBARUSDT
      - DOGEFDUSD
      - SHIBUSDT
      - LTCUSDT
      - SOLUSDC
      - PENGUUSDT
      - TNSRUSDT
      - METUSDT
      - XRPUSDC
      - NEARUSDT
      - PARTIUSDT
      - SUIUSDC
      - ADAUSDT
      - ASTERUSDT
      - UNIUSDT
      - SPKUSDT
      - AAVEUSDT
      - TAOUSDT
      - VIRTUALUSDT
      - WLFIUSDT
      - 1000CHEEMSUSDT
      - STRKUSDT
      - ZENUSDT
      - FETUSDT
      - DOGEUSDC
      - ETHEUR
      - ICPUSDT
      - BTCJPY
      - XLMUSDT
      - FDUSDUSDT
      - TONUSDT
      - PUMPUSDT
      - TNSRTRY
      - LTCUSDC
      - FFUSDT
      - RESOLVUSDT
      - DASHUSDT
      - BCHUSDT
      - LINKUSDT
      - ENAUSDT
      - PEPEUSDT
      - MMTUSDT
      - TRUMPUSDT
      - ZKUSDT
      - HBARUSDC
      - HEMIUSDT
      - ZECUSDC
      - MITOUSDT
      - TRXUSDT
      - AVAXUSDT
      - USDTTRY
      - PUMPUSDC
      - CAKEUSDT
      - ALLOTRY
      - ETHBTC
      - FDUSDUSDC
      - LDOUSDT
      - USUALUSDT
      - NEIROUSDT
      - BNBEUR
      - IOSTUSDT
      - BTCEUR
      - DOTUSDT
      - UNIUSDC
      - GPSUSDT
      - MAVUSDT
      - WIFUSDT
      - WLDUSDT
      - ONDOUSDT
      - FORMUSDT
      - TIAUSDT
      - NTRNUSDT
      - PNUTUSDT
      - LINEAUSDT
      - PARTITRY
      - ETCUSDT
      - SAPIENUSDT
      - PENDLEUSDT
      - XRPBTC
      - BATUSDT
      - APTUSDT
      - DYMTRY
      - CRVUSDT
      - NXPCUSDT
      - LINKUSDC
      - KMNOUSDT
      - ARBUSDT
      - ALLOUSDC
      - MIRAUSDT
      - XVGUSDT
      - ETHTRY
      - ICPUSDC
      - PAXGUSDT
      - FILUSDT
      - APEUSDT
      - SEIUSDT
      - ETHFIUSDT
      - POLUSDT
      - TAOUSDC
      - 1MBABYDOGEUSDT
      - SUIJPY
      - USDTBRL
      - XRPTRY
      - BTCTRY
      - SYRUPUSDT
      - NILUSDT
      - SOLBTC
      - ADAUSDC
      - KITEUSDT
      - EIGENUSDT
      - ORDIUSDT
      - GIGGLEUSDC
      - GIGGLETRY
      - SAHARAUSDT
      - QNTUSDT
      - PLUMEUSDT
      - GLMUSDT
      - PENGUUSDC
      - TRUMPUSDC
      - TSTUSDT
      - ACTUSDT
      - ILVUSDT
      - XRPEUR
      - ASTERUSDC
      - BOMEUSDT
      - ENAUSDC
      - BTCBRL
      - ZKCUSDT
      - ETHJPY
      - SOMIUSDT
      - QUICKUSDT
      - OPUSDT
      - TWTUSDT
      - OGUSDT
      - VIRTUALUSDC
      - EURUSDC
      - AVNTUSDT
      - EURUSDT
      - ERAUSDT
      - AAVEUSDC
      - RESOLVTRY
      - WALUSDT
      - RENDERUSDT
      - TRBUSDT
      - PROVEUSDT
      - PEPETRY
      - SKYUSDT
      - SNXUSDT
      - PROMUSDT
      - MBLUSDT
      - HOMEUSDT
      - DOGSUSDT
      - TNSRUSDC
      - FILUSDC
      - XRPJPY
      - DYMUSDT
      - KDAUSDT
      - 2ZUSDT
      - BARDUSDT
      - JTOUSDT
      - DYDXUSDT
      - BNBBTC
      - ARBUSDC
      - PERPUSDT
      - AVAXUSDC
      - SAGAUSDT
      - BCHUSDC
      - HUMAUSDT
      - ENATRY
      - SOLEUR
      - 0GUSDT
      - SAPIENTRY
      - GALAUSDT
      - INJUSDT
      - TUTUSDT
      - LINKJPY
      - MMTUSDC
      - XLMUSDC
      - GRTUSDT
      - WCTUSDT
      - 1INCHUSDT
      - PEPEUSDC
      - YBUSDT
      - GPSTRY
      - WLFIUSDC
      - LAYERUSDT
      - SUSDT
      - REIUSDT
      - AUSDT
      - FETUSDC
      - ARUSDT
      - ZENUSDC
      - BANANAS31USDC
      - RONINUSDT
      - SSVUSDT
      - ERAUSDC
      - ATOMUSDT
      - PYTHUSDT
      - XPLUSDC
      - MUBARAKUSDT
      - LINKFDUSD
      - SUSHIUSDT
      - MITOTRY
      - IOTXUSDT
      - REZUSDT
      - RSRUSDT
      - NMRUSDT
      - HEMITRY
      - FUNUSDT
      - CFXUSDT
      - BONKTRY
      - FLOKITRY
      - STRKUSDC
      - SOLVUSDT
      - ALICEUSDT
      - TRXTRY
      - DCRUSDT
      - BIOUSDT
      - COTIUSDT
      - ARKMUSDT
      - HBARTRY
      - BROCCOLI714USDT
      - ZROUSDT
      - RAYUSDT
      - VANAUSDT
      - EPICUSDT
      - APTUSDC
      - DUSKUSDT
      - VETUSDT
      - TREEUSDT
      - AIXBTUSDT
      - USDCTRY
      - TURTLEUSDT
      - ASTERTRY
      - NEARUSDC
      - ONGUSDT
      - PHBUSDT
      - ONEUSDT
      - PHAUSDT
      - PARTIUSDC
      - JUPUSDT
      - LDOUSDC
      - BNBETH
      - HFTUSDT
      - WIFTRY
      - SOLJPY
      - MINAUSDT
      - SOLTRY
      - WBTCUSDT
      - MEMEUSDT
      - DOLOUSDT
      - BBUSDT
      - TURBOUSDT
      - ALGOUSDT
      - BNBJPY
      - SIGNUSDT
      - FISUSDT
      - NILTRY
      - A2ZUSDT
      - ROSEUSDT
      - EIGENTRY
      - ZBTUSDT
      - SFPUSDT
      - ALGOUSDC
      - DASHUSDC
      - 1000SATSUSDT
      - EULUSDT
      - FLUXUSDT
      - NEOUSDT
      - FETTRY
      - SPKTRY
      - ETHBRL
      - JSTUSDT
      - BABYUSDT
      - MMTTRY
      - ETHFITRY
      - STXUSDT
      - OPENUSDC
      - MANTAUSDT
      - FLMUSDT
      - WUSDT
      - LAUSDT
      - HEMIUSDC
      - OPTRY
      - NXPCUSDC
      - SHELLUSDT
      - USUALTRY
      - PEOPLEUSDT
      - RESOLVUSDC
      - STRAXUSDT
      - ACTTRY
      - IMXUSDT
      - SCRUSDT
      - COOKIEUSDT
      - GMTUSDT
      - PIXELUSDT
      - PENGUTRY
      - RUNEUSDT
      - CELOUSDT
      - CHESSUSDT
      - LPTUSDT
      - NTRNTRY
      - WLFITRY
      - SANTOSUSDT
      - AIUSDT
      - VOXELUSDT
      - ZKUSDC
      - XTZUSDT
      - API3USDT
      - USDTARS
      - FIOUSDT
      - KMNOUSDC
      - SYRUPUSDC
      - FUSDT
      - OPENUSDT
      - IDEXUSDT
      - TURTLEUSDC
      - METUSDC
      - TRXUSDC
      - IOTAUSDT
      - SOLETH
      - HMSTRUSDT
      - WIFUSDC
      - AEVOUSDT
      - SUNUSDT
      - SCUSDT
      - ENSOUSDT
      - MANAUSDT
      - SANDUSDT
      - BANKUSDT
      - INITUSDT
      - ZECBTC
      - ALTUSDT
      - LINEAUSDC
      - ENSUSDT
      - MAVTRY
      - YFIUSDT
      - SUITRY
      - KAITOUSDT
      - EDUUSDT
      - SIGNFDUSD
      - BERAUSDT
      - IQUSDT
      - DOTUSDC
      - HEIUSDT
      - VTHOUSDT
      - RENDERUSDC
      - ALPINEUSDT
      - AXSUSDT
      - CETUSUSDT
      - AVAUSDT
      - STRKTRY
      - AXLUSDT
      - MOVEUSDT
      - HOOKUSDT
      - DEXEUSDT
      - MORPHOUSDT
      - USDCPLN
      - OMUSDT
      - BONKUSDC
      - IOUSDT
      - PROVEUSDC
      - EDENUSDT
      - DEGOUSDT
      - ONDOUSDC
      - ADAJPY
      - SYSUSDT
      - LUNCUSDT
      - CELOTRY
      - BMTUSDT
      - BFUSDUSDT
      - RUNEUSDC
      - BANANAUSDT
      - AVNTUSDC
      - NOTUSDT
      - RAYUSDC
      - JASMYUSDT
      - SAPIENUSDC
      - STXTRY
      - GPSUSDC
      - PENDLEUSDC
      - DOGETRY
      - KITEUSDC
      - 2ZUSDC
      - SEIUSDC
      - WBETHUSDT
      - MLNUSDT
      - NEIROTRY
      - PNUTTRY
      - AVAXTRY
      - SANTOSTRY
      - TONUSDC
      - EURIUSDT
      - XRPETH
      - ALCXUSDT
      - DATAUSDT
      - CTSIUSDT
      - ACHUSDT
      - CATIUSDT
      - USDCBRL
      - PSGUSDT
      - BCHBTC
      - KAIAUSDT
      - INJUSDC
      - WALUSDC
      - ZKCTRY
      - SUPERUSDT
      - LAYERTRY
      - XVSUSDT
      - BNBTRY
      - MOVRUSDT
      - USDTMXN
      - KERNELUSDT
      - REDUSDT
      - YGGUSDT
      - CHZUSDT
      - SUIFDUSD
      - PYRUSDT
      - MIRATRY
      - FORMTRY
      - SKLUSDT
      - 2ZTRY
      - HOTUSDT
      - BBTRY
      - FLOKIUSDC
      - CHRUSDT
      - CUSDT
      - SPELLUSDT
      - MASKUSDT
      - CITYUSDT
      - SAGAUSDC
      - XPLTRY
      - SOLBRL
      - CRVUSDC
      - SHIBUSDC
      - CKBUSDT
      - CELRUSDT
      - THETAUSDT
      - PIVXUSDT
      - SUIEUR
      - SYNUSDT
      - WLDTRY
      - VELODROMEUSDT
      - NEXOUSDT
      - EURIUSDC
      - 0GUSDC
      - XAIUSDT
      - ADAFDUSD
      - LUNAUSDT
      - EIGENUSDC
      - SHIBJPY
      - LINEATRY
      - ATMUSDT
      - KITETRY
      - CTKUSDT
      - AUDIOUSDT
      - BICOUSDT
      - MANTATRY
      - COWUSDT
      - BNSOLUSDT
      - FIDAUSDT
      - MAGICUSDT
      - RAREUSDT
      - SXTUSDT
      - WLDUSDC
      - PUMPTRY
      - METISUSDT
      - ZKTRY
      - ATOMUSDC
      - WINUSDT
      - DOGEEUR
      - NOMUSDT
      - HOLOUSDT
      - ADAEUR
      - KAITOTRY
      - VANRYUSDT
      - XNOUSDT
      - LTCEUR
      - HYPERUSDT
      - KAVAUSDT
      - ANIMEUSDT
      - DOGEJPY
      - USDTCOP
      - CYBERUSDT
      - CAKEUSDC
      - C98USDT
      - XRPBRL
      - ALICETRY
      - ZILUSDT
      - HIGHUSDT
      - ACMUSDT
      - WBTCBTC
      - FFUSDC
      - NFPUSDT
      - ICXUSDT
      - REZTRY
      - COMPTRY
      - METTRY
      - TOWNSUSDT
      - LUNCTRY
      - BEAMXUSDT
      - MBOXUSDT
      - RVNUSDT
      - ERABNB
      - SOPHUSDT
      - KSMUSDT
      - GUNUSDT
      - USDTZAR
      - ARDRUSDT
      - ASRUSDT
      - SSVUSDC
      - SUIBTC
      - VICUSDT
      - NKNUSDT
      - UTKUSDT
      - SLPUSDT
      - MAVUSDC
      - TLMUSDT
      - 0GTRY
      - THEUSDT
      - LAZIOUSDT
      - MDTUSDT
      - NEWTUSDT
      - TKOUSDT
      - OPUSDC
      - ZRXUSDT
      - COSUSDT
      - CETUSUSDC
      - YBUSDC
      - USUALUSDC
      - ERAFDUSD
      - SXPUSDT
      - BMTTRY
      - SHIBTRY
      - GTCUSDT
      - BTTCUSDT
      - LUMIAUSDT
      - TAOTRY
      - PORTALUSDT
      - JUVUSDT
      - ADATRY
      - BCHFDUSD
      - FARMUSDT
      - ACTUSDC
      - BANKTRY
      - DFUSDT
      - REQUSDT
      - PHBTRY
      - TIAUSDC
      - ETHFIUSDC
      - HUMAUSDC
      - JUPUSDC
      - STGUSDT
      - PNUTUSDC
      - ACAUSDT
      - FTTUSDT
      - USDTDAI
      - BARUSDT
      - COMPUSDT
      - ANKRUSDT
      - DGBUSDT
      - GNOUSDT
      - SNXTRY
      - APETRY
      - LISTAUSDT
      - HOMETRY
      - FLUXUSDC
      - CGPTUSDT
      - AMPUSDT
      - SCRTUSDT
      - RADUSDT
      - WCTUSDC
      - LTCBTC
      - OGNUSDT
      - AAVEFDUSD
      - FLOWUSDT
      - DUSDT
      - LSKUSDT
      - NILUSDC
      - SOMIUSDC
      - ACEUSDT
      - RIFUSDT
      - BONKFDUSD
      - TRXBTC
      - MIRABNB
      - WANUSDT
      - QKCUSDT
      - ACXUSDT
      - STOUSDT
      - TREETRY
      - BNSOLSOL
      - WTRY
      - BIGTIMEUSDT
      - LINKTRY
      - PROVETRY
      - SUSDC
      - ASTRUSDT
      - QIUSDT
      - PORTOUSDT
      - AGLDUSDT
      - FUSDC
      - USDPUSDT
      - BTCEURI
      - 1000CATUSDT
      - ADXUSDT
      - OSMOUSDT
      - BLURUSDT
      - GLMRUSDT
      - SOLVUSDC
      - ARKUSDT
      - LQTYUSDT
      - EGLDUSDT
      - DYDXTRY
      - PUNDIXUSDT
      - ONTUSDT
      - PEPEFDUSD
      - PYTHTRY
      - SPELLTRY
      - XECUSDT
      - STORJUSDT
      - XLMTRY
      - POLUSDC
      - CVCUSDT
      - TRBTRY
      - BIOTRY
      - PLUMETRY
      - INJTRY
      - LINKBTC
      - 1000SATSUSDC
      - BANDUSDT
      - LTCTRY
      - TIATRY
      - TRUUSDT
      - GHSTUSDT
      - USDTUSD
      - CVXUSDT
      - ZECETH
      - ARPAUSDT
      - GALAUSDC
      - PLUMEUSDC
      - DOGEBTC
      - LINKEUR
      - PENDLETRY
      - TUSDT
      - TURBOTRY
      - FFTRY
      - TFUELUSDT
      - ACETRY
      - XVGTRY
      - AVAXFDUSD
      - ADABTC
      - MINATRY
      - USDCRON
      - EUREURI
      - LTCFDUSD
      - UMAUSDT
      - HIVEUSDT
      - AUCTIONUSDT
      - BELUSDT
      - AWEUSDT
      - MIRAUSDC
      - ARUSDC
      - API3TRY
      - ARBTRY
      - USDTPLN
      - AVAXBTC
      - DENTUSDT
      - DODOUSDT
      - LATRY
      - ATAUSDT
      - PYTHUSDC
      - ENJUSDT
      - GRTTRY
      - PIXELTRY
      - TAOFDUSD
      - TONBTC
      - HOTTRY
      - USD1USDT
      - ENAFDUSD
      - SPKUSDC
      - TRUMPTRY
      - JOEUSDT
      - ARKMTRY
      - FORTHUSDT
      - GMXUSDT
      - HOMEUSDC
      - TURBOUSDC
      - SCRTRY
      - IOTRY
      - ALPINETRY
      - FFFDUSD
      - XLMETH
      - OMTRY
      - JTOUSDC
      - REDTRY
      - SNMBTC
      - DNTBTC
      - BTGBTC
      - XMRBTC
      - WABIBTC
      - NEBLBTC
      - QLCBTC
      - REPBTC
      - EOSUSDT
      - NULSUSDT
      - POLYBTC
      - EOSUSDC
      - WAVESUSDT
      - XMRUSDT
      - OMGUSDT
      - MITHUSDT
      - MATICUSDT
      - FTMUSDT
      - GTOUSDT
      - COCOSUSDT
      - TOMOUSDT
      - PERLUSDT
      - KEYUSDT
      - DOCKUSDT
      - BNBBUSD
      - BTCBUSD
      - BUSDUSDT
      - BEAMUSDT
      - RENUSDT
      - ETHBUSD
      - CTXCUSDT
      - TROYUSDT
      - VITEUSDT
      - FTTBTC
      - BUSDTRY
      - DREPUSDT
      - TCTUSDT
      - WRXUSDT
      - BTSUSDT
      - LTOUSDT
      - AIONUSDT
      - STPTUSDT
      - WTCUSDT
      - SOLBUSD
      - BTCUPUSDT
      - BTCDOWNUSDT
      - STMXUSDT
      - PNTBTC
      - PNTUSDT
      - BTCGBP
      - ETHGBP
      - ETHUPUSDT
      - ETHDOWNUSDT
      - ADAUPUSDT
      - ADADOWNUSDT
      - LINKUPUSDT
      - LINKDOWNUSDT
      - GBPUSDT
      - MKRUSDT
      - BTCAUD
      - ETHAUD
      - AUDBUSD
      - BNBUPUSDT
      - AUDUSDT
      - BALUSDT
      - BLZUSDT
      - IRISUSDT
      - KMDUSDT
      - SRMBUSD
      - SRMUSDT
      - ANTUSDT
      - OCEANBTC
      - OCEANUSDT
      - WNXMUSDT
      - YFIIUSDT
      - XRPUPUSDT
      - XRPDOWNUSDT
      - DOTUPUSDT
      - DOTDOWNUSDT
      - USDTNGN
      - WINGUSDT
      - CREAMBUSD
      - UNIBUSD
      - NBSUSDT
      - HNTBTC
      - HNTUSDT
      - CAKEBUSD
      - ORNUSDT
      - UTKBTC
      - ALPHAUSDT
      - AKROUSDT
      - HARDUSDT
      - DNTBUSD
      - DNTUSDT
      - UNFIUSDT
      - XEMUSDT
      - REEFUSDT
      - BTCSTBUSD
      - BTCSTUSDT
      - USDCBUSD
      - FIROUSDT
      - BETHETH
      - LITUSDT
      - DOGEGBP
      - BADGERUSDT
      - LINAUSDT
      - EOSTRY
      - AUTOBUSD
      - AUTOUSDT
      - BTGBUSD
      - BTGUSDT
      - MIRBTC
      - MIRBUSD
      - MIRUSDT
      - BAKEUSDT
      - BURGERUSDT
      - POLSUSDT
      - MDXUSDT
      - MASKBUSD
      - AGIXBTC
      - TORNBTC
      - TORNBUSD
      - TORNUSDT
      - HNTBUSD
      - FTTBUSD
      - ERNUSDT
      - KLAYUSDT
      - BONDBTC
      - BONDUSDT
      - CLVUSDT
      - FLOWBUSD
      - TVKUSDT
      - ALPACAUSDT
      - VGXBTC
      - VGXETH
      - FORUSDT
      - OGNBUSD
      - POLYBUSD
      - ELFUSDT
      - DYDXBUSD
      - POLYUSDT
      - VIDTUSDT
      - FRONTUSDT
      - CVPUSDT
      - BETAUSDT
      - REEFTRY
      - DARUSDT
      - BNXUSDT
      - KP3RUSDT
      - VGXUSDT
      - PLAUSDT
      - RNDRBTC
      - RNDRUSDT
      - RNDRBUSD
      - MCUSDT
      - COCOSBUSD
      - BICOBUSD
      - FTMTRY
      - OOKIUSDT
      - COCOSTRY
      - JASMYETH
      - LOKAUSDT
      - ANCBTC
      - ANCBUSD
      - ANCUSDT
      - DARTRY
      - GMTBUSD
      - APEBUSD
      - BSWUSDT
      - MULTIUSDT
      - WAVESTRY
      - BSWTRY
      - MOBUSDT
      - GALUSDT
      - GALTRY
      - EPXUSDT
      - REIBUSD
      - LUNCBUSD
      - OPBUSD
      - GTOBUSD
      - LEVERUSDT
      - SNMBUSD
      - GASBUSD
      - NEBLBUSD
      - NEBLUSDT
      - HIFIUSDT
      - PROSUSDT
      - GFTBUSD
      - AGIXUSDT
      - VIBUSDT
      - AMBUSDT
      - UFTUSDT
      - AGIXTRY
      - LOOMUSDT
      - OAXUSDT
      - AERGOUSDT
      - RNDRTRY
      - ASTUSDT
      - SNTUSDT
      - COMBOUSDT
      - COMBOTRY
      - FDUSDBUSD
      - TOMOTRY
      - UNFITRY
      - CREAMUSDT
      - GFTUSDT
      - FRONTTRY
      - LEVERTRY
      - RNDRFDUSD
      - MATICUSDC
      - PDAUSDT
      - OMNIUSDT
      - OMNITRY
      - OMNIUSDC
      - BAKETRY
      - BNXTRY
      - SLFTRY
      - SLFUSDC
      - SLFUSDT
      - STMXTRY
      - TROYTRY
      - TROYUSDC
      - BNXUSDC
      - EOSETH
      - SNTETH
      - BNTETH
      - WTCBTC
      - OMGBTC
      - OMGETH
      - ZRXETH
      - KNCETH
      - FUNETH
      - NEOETH
      - MTLETH
      - EOSBTC
      - SNTBTC
      - BNTBTC
      - ASTBTC
      - OAXBTC
      - VIBBTC
      - VIBETH
      - ARKBTC
      - ENJETH
      - KMDBTC
      - NULSBTC
      - XMRETH
      - AMBBTC
      - BATETH
      - NEOBNB
      - BTSBTC
      - LSKETH
      - IOTABNB
      - XLMBNB
      - WAVESBTC
      - WAVESETH
      - WAVESBNB
      - GTOBTC
      - ICXETH
      - ELFBTC
      - ELFETH
      - AIONBTC
      - IOSTBTC
      - IOSTETH
      - BLZBTC
      - BLZETH
      - ZILBTC
      - ZILBNB
      - ONTETH
      - XEMBTC
      - WANETH
      - LOOMBTC
      - LOOMETH
      - ZENETH
      - ZENBNB
      - EOSBNB
      - CVCBTC
      - THETAETH
      - THETABNB
      - QKCBTC
      - QKCETH
      - ENJBNB
      - DATABTC
