apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tokio-symbols
  namespace: backend
data:
  symbols-config.yaml: |
    symbols:
      - ETHUSDT
      - BTCUSDT
      - FLOKIUSDT
      - XRPUSDT
      - BREVUSDT
      - DOGEUSDT
      - SOLUSDT
      - BTCFDUSD
      - BNBUSD1
      - BONKUSDT
      - BNBUSDT
      - ETHFDUSD
      - SUIUSDT
      - ETHUSDC
      - BTCUSDC
      - SHIBUSDT
      - SPKUSDT
      - SOLFDUSD
      - USDCUSDT
      - VIRTUALUSDT
      - BNBUSDC
      - BNBFDUSD
      - DOGEFDUSD
      - PENGUUSDT
      - PEPEUSDT
      - BROCCOLI714USDT
      - XPLUSDT
      - ZECUSDT
      - ADAUSDT
      - TAOUSDT
      - FETUSDT
      - BREVTRY
      - LTCUSDT
      - USD1USDT
      - SUIUSDC
      - XRPFDUSD
      - NEIROUSDT
      - HBARUSDT
      - OGUSDT
      - ZKPUSDT
      - ENAUSDT
      - GIGGLEUSDT
      - 1000CHEEMSUSDT
      - RENDERUSDT
      - XRPUSDC
      - WLDUSDT
      - BTCUSD1
      - NEARUSDT
      - PUMPUSDT
      - FDUSDUSDC
      - SOLUSDC
      - UNIUSDT
      - "\u5E01\u5B89\u4EBA\u751FUSDT"
      - AAVEUSDT
      - TIAUSDT
      - JASMYUSDT
      - FDUSDUSDT
      - BREVUSDC
      - TRUMPUSDT
      - XLMUSDT
      - WIFUSDT
      - AVAXUSDT
      - USDTTRY
      - ASTERUSDT
      - FILUSDT
      - BTCJPY
      - BABYUSDT
      - ZKUSDT
      - WLFIUSD1
      - DOTUSDT
      - LINKUSDT
      - ZENUSDT
      - TRXUSDT
      - BCHUSDT
      - ICPUSDT
      - BNBEUR
      - WLFIUSDT
      - HBARUSDC
      - ONDOUSDT
      - DOGEUSDC
      - INJUSDT
      - PEPEUSDC
      - KAITOUSDT
      - FFUSDT
      - A2ZUSDT
      - PEPETRY
      - PENGUUSDC
      - GUNUSDT
      - ETHUSD1
      - LDOUSDT
      - APTUSDT
      - TONUSDT
      - CAKEUSDT
      - PAXGUSDT
      - ADAUSDC
      - ETCUSDT
      - ZKPTRY
      - 1MBABYDOGEUSDT
      - PNUTUSDT
      - ENAUSDC
      - SEIUSDT
      - ATUSDT
      - MBLUSDT
      - KITEUSDT
      - CRVUSDT
      - XRPEUR
      - ORDIUSDT
      - POLUSDT
      - CUSDT
      - SYRUPUSDT
      - ETHBTC
      - DASHUSDT
      - AMPUSDT
      - LUNCUSDT
      - EURUSDC
      - PENDLEUSDT
      - TAOUSDC
      - 2ZUSDT
      - VIRTUALUSDC
      - ARBUSDT
      - RENDERUSDC
      - PROMUSDT
      - LINKUSDC
      - SNXUSDT
      - USDTBRL
      - XRPTRY
      - BTCEUR
      - ACHUSDT
      - OPUSDT
      - ETHTRY
      - BOMEUSDT
      - GUSDT
      - ZECUSDC
      - MUBARAKUSDT
      - GALAUSDT
      - ZBTUSDT
      - ETHFIUSDT
      - STXUSDT
      - OGTRY
      - FORMUSDT
      - BBUSDT
      - EURUSDT
      - BNBBTC
      - GRTUSDT
      - EIGENUSDT
      - FUNUSDT
      - TURBOUSDT
      - KMNOUSDT
      - QNTUSDT
      - CHZUSDT
      - EULUSDT
      - XPLUSDC
      - ATOMUSDT
      - SSVUSDT
      - RADUSDT
      - ETHEUR
      - DOGEUSD1
      - SOLBTC
      - ANIMEUSDT
      - LINEAUSDT
      - SPKTRY
      - RSRUSDT
      - BIFIUSDT
      - TSTUSDT
      - AIXBTUSDT
      - APEUSDT
      - ADAUSD1
      - RAYUSDT
      - PARTIUSDT
      - SUSDT
      - PROVEUSDT
      - ARKMUSDT
      - CVCUSDT
      - TREEUSDT
      - SOLJPY
      - USDTARS
      - THEUSDT
      - GIGGLEUSDC
      - LTCUSDC
      - STRAXUSDT
      - SOMIUSDT
      - SXPUSDT
      - TWTUSDT
      - AVNTUSDT
      - LUNAUSDT
      - BROCCOLI714USDC
      - ZROUSDT
      - USD1USDC
      - TRXTRY
      - ARUSDT
      - STRKUSDT
      - BARDUSDT
      - SUIJPY
      - REDUSDT
      - SANDUSDT
      - GIGGLETRY
      - ENSUSDT
      - BTCBRL
      - TOWNSUSDT
      - XRPBTC
      - TLMUSDT
      - SOLEUR
      - PEOPLEUSDT
      - BONKTRY
      - MORPHOUSDT
      - TUTUSDT
      - CELRUSDT
      - XRPJPY
      - DYDXUSDT
      - HOMEUSDT
      - FETUSDC
      - BANANAS31USDT
      - DOGSUSDT
      - BABYTRY
      - BCHUSDC
      - ETHJPY
      - SOLUSD1
      - BIOUSDT
      - MMTUSDT
      - ACTUSDT
      - ENSOUSDT
      - BTCTRY
      - ALGOUSDT
      - DOLOUSDT
      - PLUMEUSDT
      - AVAXUSDC
      - WALUSDT
      - XAIUSDT
      - JASMYTRY
      - FLOKITRY
      - VETUSDT
      - AEVOUSDT
      - GMTUSDT
      - CYBERUSDT
      - HUMAUSDT
      - AAVEUSDC
      - ALLOUSDT
      - SCUSDT
      - XTZUSDT
      - TRBUSDT
      - UNIUSDC
      - ASTERUSD1
      - APTUSDC
      - DOTUSDC
      - ZKPUSDC
      - METISUSDT
      - SUIUSD1
      - IMXUSDT
      - BONKUSDC
      - PUMPUSDC
      - METUSDT
      - XLMUSDC
      - JUPUSDT
      - XRPBRL
      - FLOKIUSDC
      - ALTUSDT
      - MEMEUSDT
      - LPTUSDT
      - USDCPLN
      - USDTCOP
      - HMSTRUSDT
      - DOGETRY
      - SAPIENUSDT
      - YBUSDT
      - SKYUSDT
      - HEMIUSDT
      - NEARUSDC
      - NEOUSDT
      - WIFUSDC
      - CTKUSDT
      - IQUSDT
      - RADTRY
      - SOLVUSDT
      - CFXUSDT
      - FLOWUSDT
      - ALGOUSDC
      - 0GUSDT
      - DOGEEUR
      - MANTAUSDT
      - BBTRY
      - WLDUSDC
      - SPELLUSDT
      - QKCUSDT
      - INJUSDC
      - ZKCUSDT
      - MITOUSDT
      - USDTZAR
      - IOTAUSDT
      - USDTMXN
      - ACEUSDT
      - BANANAUSDT
      - KERNELUSDT
      - JTOUSDT
      - SOLTRY
      - USDTIDR
      - SIGNUSDT
      - BATUSDT
      - MLNUSDT
      - OMUSDT
      - QTUMUSDT
      - BIGTIMEUSDT
      - MAVUSDT
      - COOKIEUSDT
      - SAGAUSDT
      - SUNUSDT
      - OPENUSDT
      - ADAJPY
      - TRUMPUSDC
      - PORTALUSDT
      - BMTUSDT
      - MEUSDT
      - RESOLVUSDT
      - EDUUSDT
      - SHIBUSDC
      - USDCTRY
      - FILUSDC
      - XVGUSDT
      - RUNEUSDT
      - ETHBRL
      - CGPTUSDT
      - ARBUSDC
      - CKBUSDT
      - ERAUSDT
      - LINKJPY
      - MANAUSDT
      - NFPUSDT
      - AMPTRY
      - USUALUSDT
      - AUCTIONUSDT
      - AUSDT
      - DIAUSDT
      - DYMUSDT
      - KAIAUSDT
      - PYTHUSDT
      - ICPUSDC
      - LUMIAUSDT
      - CVXUSDT
      - SYRUPUSDC
      - SUSHIUSDT
      - CELOUSDT
      - TRXUSDC
      - TNSRUSDT
      - SOPHUSDT
      - GASUSDT
      - IDEXUSDT
      - USDCBRL
      - ARDRUSDT
      - XRPUSD1
      - DATAUSDT
      - LINKFDUSD
      - NILUSDT
      - SUIEUR
      - POLYXUSDT
      - PIXELUSDT
      - BNBJPY
      - HOTUSDT
      - NMRUSDT
      - VANAUSDT
      - 1000SATSUSDT
      - WBTCUSDT
      - COTIUSDT
      - ACHTRY
      - FETTRY
      - KNCUSDT
      - YGGUSDT
      - SEIUSDC
      - SKLUSDT
      - LAYERUSDT
      - IOUSDT
      - EURIUSDT
      - PEPEFDUSD
      - USTCUSDT
      - GLMUSDT
      - SAHARAUSDT
      - FIDAUSDT
      - AVAXTRY
      - LISTAUSDT
      - WCTUSDT
      - TFUELUSDT
      - COMPUSDT
      - NOTUSDT
      - AXSUSDT
      - WUSDT
      - ZKUSDC
      - ASRUSDT
      - NOMUSDT
      - ROSEUSDT
      - API3USDT
      - ZKTRY
      - BNSOLUSDT
      - PEPEJPY
      - CETUSUSDT
      - SUITRY
      - ARKUSDT
      - WAXPUSDT
      - GMXUSDT
      - USDTPLN
      - HIVEUSDT
      - UMAUSDT
      - SANTOSUSDT
      - PIVXUSDT
      - CRVUSDC
      - STEEMUSDT
      - PENGUTRY
      - SHIBJPY
      - RENDERTRY
      - ICXUSDT
      - AUDIOUSDT
      - BICOUSDT
      - SOLETH
      - ASTERUSDC
      - SHIBTRY
      - WIFTRY
      - BLURUSDT
      - STORJUSDT
      - BNBETH
      - BEAMXUSDT
      - JSTUSDT
      - BNBTRY
      - THETAUSDT
      - WLFITRY
      - NEWTUSDT
      - XPLTRY
      - DUSKUSDT
      - LUNATRY
      - MINAUSDT
      - ASTERTRY
      - ATOMUSDC
      - GTRY
      - WLFIUSDC
      - KSMUSDT
      - SPKUSDC
      - GPSUSDT
      - WINUSDT
      - MOVRUSDT
      - EIGENTRY
      - BANKUSDT
      - BERAUSDT
      - SUPERUSDT
      - JOEUSDT
      - ADAEUR
      - FORTHUSDT
      - INITUSDT
      - ALPINEUSDT
      - TURTLEUSDT
      - AIUSDT
      - STOUSDT
      - NXPCUSDT
      - EGLDUSDT
      - RUNEUSDC
      - SXPTRY
      - HBARTRY
      - DOGSUSDC
      - EDENUSDT
      - MIRAUSDT
      - SNXTRY
      - KMNOUSDC
      - CAKEUSDC
      - FLUXUSDT
      - XRPETH
      - ALICEUSDT
      - TOWNSTRY
      - USDTUSD
      - ONEUSDT
      - LUNCTRY
      - MASKUSDT
      - SXTUSDT
      - CHESSUSDT
      - NEXOUSDT
      - TLMTRY
      - PUMPTRY
      - USDTDAI
      - AXLUSDT
      - ZILUSDT
      - MAGICUSDT
      - DCRUSDT
      - ALCXUSDT
      - ENATRY
      - REZUSDT
      - YFIUSDT
      - DGBUSDT
      - PROVEUSDC
      - FUSDT
      - WBETHUSDT
      - ACAUSDT
      - MOVEUSDT
      - DEXEUSDT
      - EPICUSDT
      - ACTTRY
      - ASTRUSDT
      - AVAXUSD1
      - RVNUSDT
      - COWUSDT
      - PHAUSDT
      - ADAFDUSD
      - FARMUSDT
      - 2ZUSDC
      - RONINUSDT
      - DOGEJPY
      - DEGOUSDT
      - XECUSDT
      - WBTCBTC
      - LAUSDT
      - HOOKUSDT
      - SYNUSDT
      - WALUSDC
      - PENDLEUSDC
      - TUSDT
      - ANIMETRY
      - TREETRY
      - BELUSDT
      - SPELLTRY
      - TRUUSDT
      - ADATRY
      - OXTUSDT
      - LPTTRY
      - 1000CATUSDT
      - PYRUSDT
      - SUIBTC
      - STGUSDT
      - EUREURI
      - RPLUSDT
      - VTHOUSDT
      - BABYUSDC
      - ZECBTC
      - SHELLUSDT
      - ERAFDUSD
      - OSMOUSDT
      - ZRXUSDT
      - KAVAUSDT
      - ONTUSDT
      - UTKUSDT
      - TRXBTC
      - CATIUSDT
      - DODOUSDT
      - NTRNUSDT
      - BTTCUSDT
      - RAREUSDT
      - ZBTTRY
      - SUIFDUSD
      - SAPIENTRY
      - MTLUSDT
      - SLPUSDT
      - IDUSDT
      - JTOUSDC
      - BFUSDUSDT
      - FTTUSDT
      - AGLDUSDT
      - HYPERUSDT
      - SOLVBNB
      - ACETRY
      - ETHFITRY
      - IOTXUSDT
      - QUICKUSDT
      - HAEDALUSDT
      - RAYUSDC
      - SUSDC
      - HEIUSDT
      - "\u5E01\u5B89\u4EBA\u751FUSDC"
      - TIAUSDC
      - SFPUSDT
      - BTCMXN
      - PONDUSDT
      - POWRUSDT
      - STRAXTRY
      - MDTUSDT
      - BARUSDT
      - FIOUSDT
      - VELODROMEUSDT
      - SOLBRL
      - LINKEUR
      - VICUSDT
      - PHBUSDT
      - WOOUSDT
      - LQTYUSDT
      - JUVUSDT
      - HFTUSDT
      - EULUSDC
      - SCRTUSDT
      - HOLOUSDT
      - MBOXUSDT
      - XVSUSDT
      - REDTRY
      - ONDOUSDC
      - WLDTRY
      - 2ZTRY
      - ORCAUSDT
      - COSUSDT
      - RLCUSDT
      - 1INCHUSDT
      - DOGSTRY
      - STRKUSDC
      - LAZIOUSDT
      - ILVUSDT
      - ENJUSDT
      - MMTUSDC
      - PAXGUSDC
      - CTRY
      - LINEAUSDC
      - AVAUSDT
      - TIATRY
      - LSKUSDT
      - IOSTUSDT
      - GLMRUSDT
      - CITYUSDT
      - POLUSDC
      - ONGUSDT
      - USDCRON
      - BOMEUSDC
      - USDTUAH
      - XAITRY
      - VANRYUSDT
      - GUNTRY
      - TKOUSDT
      - ACXUSDT
      - PNUTTRY
      - LRCUSDT
      - TONUSDC
      - ATMUSDT
      - SOLBNB
      - EIGENUSDC
      - OPUSDC
      - VANRYTRY
      - BTCZAR
      - ANIMEUSDC
      - MUBARAKTRY
      - DFUSDT
      - C98USDT
      - FFUSDC
      - CHRUSDT
      - EURIUSDC
      - MMTTRY
      - ZENUSDC
      - BCHUSD1
      - DYDXTRY
      - HIGHUSDT
      - QIUSDT
      - ONETRY
      - ERAUSDC
      - JUPUSDC
      - GUNUSDC
      - PEPEBRL
      - GALATRY
      - SCRUSDT
      - PSGUSDT
      - REQUSDT
      - NKNUSDT
      - BIOTRY
      - ZBTUSDC
      - GNOUSDT
      - SNXUSDC
      - GNSUSDT
      - WALTRY
      - AWEUSDT
      - TAOTRY
      - TAOBTC
      - DOGEBTC
      - GALAUSDC
      - ANKRUSDT
      - NEIROUSDC
      - TRXETH
      - RIFUSDT
      - EULTRY
      - UNIUSD1
      - MEMETRY
      - HEMIUSDC
      - AVAXBTC
      - BANDUSDT
      - DENTUSDT
      - TNSRTRY
      - LINKBTC
      - FXSUSDT
      - ADXUSDT
      - NEIROTRY
      - REDUSDC
      - BTCEURI
      - PORTALTRY
      - CETUSUSDC
      - INJTRY
      - WALBNB
      - SAPIENUSDC
      - BTCIDR
      - XNOUSDT
      - TRUMPTRY
      - AVNTTRY
      - BNSOLSOL
      - ACMUSDT
      - WBETHETH
      - ARUSDC
      - SSVUSDC
      - BMTTRY
      - THETRY
      - HOTTRY
      - STXUSDC
      - DUSDT
      - BCHBTC
      - ARKMUSDC
      - VICTRY
      - PAXGTRY
      - PNUTUSDC
      - MORPHOUSDC
      - PARTITRY
      - PUNDIXUSDT
      - GRTTRY
      - PAXGBTC
      - FORMTRY
      - VIRTUALTRY
      - RDNTUSDT
      - LTCEUR
      - ARPAUSDT
      - HMSTRTRY
      - AAVETRY
      - THEUSDC
      - ACTUSDC
      - TREEUSDC
      - LTCBTC
      - XTZUSDC
      - VANRYUSDC
      - GUNFDUSD
      - HOMETRY
      - ORDIUSDC
      - AEVOTRY
      - OGNUSDT
      - RENDERBTC
      - ZROUSDC
      - SYSUSDT
      - BNTUSDT
      - PEOPLEUSDC
      - DYDXUSDC
      - WCTUSDC
      - 1000SATSUSDC
      - ARKMTRY
      - SKYUSDC
      - BNBBRL
      - CUSDC
      - SOMIUSDC
      - LINKTRY
      - USDCCZK
      - EDUTRY
      - FFFDUSD
      - PORTOUSDT
      - 0GUSDC
      - XLMTRY
      - ASRTRY
      - PEPEEUR
      - HEMITRY
      - AUCTIONTRY
      - BTCUSD
      - DASHUSDC
      - ATTRY
      - GMTTRY
      - AVNTUSDC
      - TRUTRY
      - BERAUSDC
      - TSTTRY
      - LISTATRY
      - NEXOBTC
      - BOMETRY
      - A2ZUSDC
      - CTSIUSDT
      - WTRY
      - TOWNSUSDC
      - MAVTRY
      - ICPTRY
      - CHZTRY
      - IOTAUSDC
      - ARBTRY
      - ZKCUSDC
      - XRPBNB
      - SANDTRY
      - KERNELTRY
      - PYTHUSDC
      - AIXBTTRY
      - ADABRL
      - WALFDUSD
      - ZKCTRY
      - BBUSDC
      - FILTRY
      - COWTRY
      - CYBERTRY
      - ACATRY
      - CYBERUSDC
      - TSTUSDC
      - IOTATRY
      - POLYXTRY
      - ALTUSDC
      - LTCTRY
      - ADAETH
      - BTCPLN
      - BIOUSDC
      - NEWTFDUSD
      - JTOTRY
      - USUALUSDC
      - AEURUSDT
      - KERNELUSDC
      - ADABTC
      - FETBTC
      - JUPTRY
      - MITOTRY
      - RENDERFDUSD
      - SOMITRY
      - TURBOTRY
      - ATAUSDT
      - LUMIATRY
      - AUDIOTRY
      - KGSTUSDT
      - LTCFDUSD
      - SIGNBNB
      - POLTRY
      - WUSDC
      - RSRUSDC
      - USTCTRY
      - TRBUSDC
      - FETFDUSD
      - PENGUFDUSD
      - SANTOSTRY
      - MINATRY
      - USDEUSDT
      - GTCUSDT
      - MEMEUSDC
      - TURBOUSDC
      - KAITOTRY
      - SANDUSDC
      - UNIFDUSD
      - 1000CATTRY
      - BREVBNB
      - OMUSDC
      - WANUSDT
      - AAVEETH
      - TRXEUR
      - SIGNUSDC
      - SHIBEUR
      - LINEATRY
      - TRXJPY
      - OMTRY
      - ALPINETRY
      - GHSTUSDT
      - IOTRY
      - NOTUSDC
      - BEAMXTRY
      - IOUSDC
      - FIDATRY
      - CHZUSDC
      - CETUSTRY
      - TONTRY
      - TRXXRP
      - BANANAS31USDC
      - HMSTRUSDC
      - DOTBTC
      - LINKETH
      - 0GTRY
      - RARETRY
      - SOLIDR
      - AAVEBTC
      - TUSDUSDT
      - XLMBTC
      - FUSDC
      - AVAXETH
      - HOMEUSDC
      - APEUSDC
      - REZTRY
      - SEITRY
      - SYRUPTRY
      - TUTUSDC
      - MINAUSDC
      - EGLDUSDC
      - BFUSDUSDC
      - ENAFDUSD
      - APTTRY
      - ENSUSDC
      - STRY
      - USDCUSD
      - 1000SATSTRY
      - BTTCTRY
      - NEARBTC
      - ORDITRY
      - INJFDUSD
      - KITETRY
      - LDOUSDC
      - LDOTRY
      - 1MBABYDOGEUSDC
      - OPENUSDC
      - SANDFDUSD
      - MUBARAKUSDC
      - THETAUSDC
      - SOPHTRY
      - UNITRY
      - "\u5E01\u5B89\u4EBA\u751FTRY"
      - VETUSDC
      - CVCUSDC
      - FLUXUSDC
      - TLMUSDC
      - HBARBTC
      - HYPERTRY
      - STORJTRY
      - FFTRY
      - ZKFDUSD
      - CRVTRY
      - ONDOTRY
      - ENSOBNB
      - BBBNB
      - ETHFIUSDC
      - SAGAUSDC
      - MANTAUSDC
      - BELTRY
      - OPTRY
      - RESOLVUSDC
      - APETRY
      - SKLTRY
      - XLMEUR
      - BANKTRY
      - MBOXTRY
      - UMATRY
      - TIAFDUSD
      - RSRTRY
      - GLMBTC
      - METRY
      - BARTRY
      - DOGEBRL
      - DOTTRY
      - LAYERTRY
      - RAYTRY
      - RAREUSDC
      - HIVETRY
      - ZECETH
      - PENDLETRY
      - STEEMBTC
      - SOLVFDUSD
      - ERABNB
      - AXLTRY
      - ICPBTC
      - STRKTRY
      - SHIBFDUSD
      - AVAXFDUSD
      - DOTEUR
      - THETABTC
      - ONTTRY
      - KAITOUSDC
      - USDCIDR
      - NOTTRY
      - MOVEUSDC
      - BEAMXUSDC
      - BLURTRY
      - ALICETRY
      - LTCETH
      - SAGATRY
      - FILFDUSD
      - PIXELTRY
      - MAGICTRY
      - ENSOUSDC
      - STXTRY
      - PHAUSDC
      - SOPHUSDC
      - PYTHTRY
      - UNIBTC
      - DAIJPY
      - REDFDUSD
      - COMPTRY
      - TRBTRY
      - GUNBNB
      - DASHTRY
      - ENSOTRY
      - QNTUSDC
      - FDUSDTRY
      - SUNTRY
      - VETTRY
      - SXTUSDC
      - ALLOTRY
      - USUALTRY
      - DYMTRY
      - ALLOUSDC
      - FTRY
      - RENDEREUR
      - SIGNFDUSD
      - WIFBTC
      - ETHPLN
      - ZROTRY
      - STOUSDC
      - JUVTRY
      - COTITRY
      - PLUMETRY
      - ALTTRY
      - CVXUSDC
      - YBTRY
      - ETHEURI
      - EPICUSDC
      - NEARTRY
      - PARTIUSDC
      - DOTFDUSD
      - LAYERUSDC
      - INITUSDC
      - API3TRY
      - AIXBTUSDC
      - PROVETRY
      - DOLOTRY
      - ARKTRY
      - ADXETH
      - CFXUSDC
      - MORPHOTRY
      - ROSETRY
