apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prometheus-kafka-pool
  namespace: backend
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - backend
  selector:
    matchLabels:
      app: kafka-pool
  podMetricsEndpoints:
    - port: tcp-prometheus
      interval: 10s
      scrapeTimeout: 5s
      path: /metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_strimzi_io_cluster]
          targetLabel: strimzi_io_cluster