apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-pvc
  namespace: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: flink-storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: flink-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  type: pd-ssd
