apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kafka-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  type: pd-ssd
