apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tokio-binance-scraper
  namespace: backend
data:
  RUST_LOG: "info"
  ENABLE_METRICS_VERBOSE: "false"
  KAFKA_CLIENT_ID: "binance-scraper"
  KAFKA_TOPIC: "binance-depthUpdate-raw"
  KAFKA_BROKER_HOST: "kafka-cluster-kafka-bootstrap.backend.svc.cluster.local:9092"
  SCHEMA_REGISTRY_URL: "http://schema-registry-cluster-ip.backend.svc.cluster.local:8081"
  EXCHANGE_SYMBOLS: FLOKIUSDT,ETHUSDT,BTCUSDT,BTCFDUSD,SOLUSDT,BONKUSDT,WCTUSDT,NEIROUSDT,XRPUSDT,DOGEUSDT,ETHFDUSD,PEPEUSDT,DOGEFDUSD,LPTUSDT,BNBUSDT,SHIBUSDT,SUIUSDT,VIRTUALUSDT,BTCUSDC,SOLFDUSD,KAITOUSDT
  BINANCE_WS_URL: "stream.binance.com:9443"
  CONFIG_ENABLE_SCRAPING: "true"
  TRACKED_SYMBOLS: "FLOKIUSDT"
  METRICS_PORT: "9000"
  TOKIO_WORKER_THREADS: "1"
  TOKIO_QUEUE_INTERVAL: "5"
  TOKIO_EVENT_INTERVAL: "5"
  PROCESS_QUEUE_CAPACITY: "1000"
  DISPATCH_QUEUE_CAPACITY: "1000"
  STREAM_GROUP_COUNT: "4"
  DISPATCH_GROUP_COUNT: "4"
  PROCESS_GROUP_COUNT: "15"
