apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tokio-symbols
  namespace: backend
data:
  symbols-config.yaml: |
    symbols:
      - FLOKIUSDT
      - ETHUSDT
      - BTCFDUSD
      - BONKUSDT
      - BTCUSDT
      - SOLUSDT
      - ETHFDUSD
      - XRPUSDT
      - TSTUSDT
      - ENAUSDT
      - DOGEUSDT
      - BNBUSDT
      - SOLFDUSD
      - LTCUSDT
      - BNBFDUSD
      - PROVEUSDT
      - DOGEFDUSD
      - ETHUSDC
      - SUIUSDT
      - TOWNSUSDT
      - SPELLUSDT
      - PENGUUSDT
      - BCHUSDT
      - USDCUSDT
      - TREEUSDT
      - SHIBUSDT
      - HBARUSDT
      - XRPFDUSD
      - SUIUSDC
      - NEIROUSDT
      - ADAUSDT
      - CFXUSDT
      - SYRUPUSDT
      - CRVUSDT
      - XRPUSDC
      - PEPEUSDT
      - SPKUSDT
      - BTCUSDC
      - OMNIUSDT
      - UNIUSDT
      - OMUSDT
      - XLMUSDT
      - FDUSDUSDT
      - EPICUSDT
      - SPELLTRY
      - ONDOUSDT
      - VIRTUALUSDT
      - ASRUSDT
      - SEIUSDT
      - TOWNSTRY
      - ILVUSDT
      - FORMUSDT
      - AVAXUSDT
      - FUNUSDT
      - OMNITRY
      - TONUSDT
      - SOLUSDC
      - ENAUSDC
      - AAVEUSDT
      - WLDUSDT
      - PROVETRY
      - LINKUSDT
      - TRXUSDT
      - PROVEUSDC
      - MKRUSDT
      - LINKFDUSD
      - FDUSDUSDC
      - TOWNSUSDC
      - PENGUUSDC
      - DYDXUSDT
      - NEARUSDT
      - PEPEUSDC
      - ORDIUSDT
      - ETHFIUSDT
      - BIOUSDT
      - WIFUSDT
      - PENDLEUSDT
      - CAKEUSDT
      - PENGUTRY
      - USDTTRY
      - POLUSDT
      - DOGEUSDC
      - ETHBTC
      - REDUSDT
      - APTUSDT
      - ERAUSDT
      - ALGOUSDT
      - BNBUSDC
      - SUSDT
      - KERNELUSDT
      - ARBUSDT
      - SPKTRY
      - BOMEUSDT
      - HBARUSDC
      - HEIUSDT
      - LDOUSDT
      - INJUSDT
      - PNUTUSDT
      - ORCAUSDT
      - INITUSDT
      - GALAUSDT
      - MAVUSDT
      - THEUSDT
      - MUBARAKUSDT
      - MAGICUSDT
      - CFXUSDC
      - FXSUSDT
      - TURBOUSDT
      - ALTUSDT
      - ETCUSDT
      - PHBUSDT
      - TRBUSDT
      - BABYUSDT
      - A2ZUSDT
      - USDTBRL
      - NXPCUSDT
      - DOTUSDT
      - HUMAUSDT
      - SAHARAUSDT
      - ADAUSDC
      - SPKUSDC
      - TSTUSDC
      - KAITOUSDT
      - ZKUSDT
      - TSTTRY
      - BANANAS31USDT
      - ETHEUR
      - OPUSDT
      - OGUSDT
      - REZUSDT
      - DEXEUSDT
      - OMTRY
      - XTZUSDT
      - RSRUSDT
      - TAOUSDT
      - LTCUSDC
      - RUNEUSDT
      - RENDERUSDT
      - STOUSDT
      - ICPUSDT
      - TRUMPUSDT
      - BTCEUR
      - 1MBABYDOGEUSDT
      - FETUSDT
      - TIAUSDT
      - BIOTRY
      - BCHUSDC
      - COSUSDT
      - PIXELUSDT
      - APEUSDT
      - MEMEUSDT
      - JUPUSDT
      - SAGAUSDT
      - CVXUSDT
      - SYRUPUSDC
      - CUSDT
      - ENSUSDT
      - RAREUSDT
      - AIXBTUSDT
      - PYRUSDT
      - EURUSDT
      - KAVAUSDT
      - ZROUSDT
      - EURUSDC
      - EIGENUSDT
      - UMAUSDT
      - HYPERUSDT
      - FIOUSDT
      - CRVUSDC
      - ARKMUSDT
      - WCTUSDT
      - RPLUSDT
      - ENATRY
      - MBLUSDT
      - HFTUSDT
      - GASUSDT
      - GPSUSDT
      - ATOMUSDT
      - UNIUSDC
      - ETHTRY
      - BANANAS31USDC
      - SIGNUSDT
      - ETHJPY
      - PEOPLEUSDT
      - ALICEUSDT
      - QNTUSDT
      - AUSDT
      - PEPETRY
      - MEUSDT
      - JTOUSDT
      - FILUSDT
      - TREEUSDC
      - VETUSDT
      - CFXTRY
      - USDCTRY
      - BONKUSDC
      - HOOKUSDT
      - CKBUSDT
      - RAYUSDT
      - RESOLVUSDT
      - BROCCOLI714USDT
      - BONKTRY
      - USUALUSDT
      - OMUSDC
      - XLMUSDC
      - AMPUSDT
      - LINKUSDC
      - KDAUSDT
      - XRPEUR
      - COMPUSDT
      - DEGOUSDT
      - BEAMXUSDT
      - VICUSDT
      - WIFUSDC
      - IOUSDT
      - XRPTRY
      - STRKUSDT
      - ACHUSDT
      - NOTUSDT
      - BMTUSDT
      - RENDERUSDC
      - SOPHUSDT
      - SXTUSDT
      - SOLBTC
      - GUNUSDT
      - CETUSUSDT
      - AVAXUSDC
      - ONGUSDT
      - BBUSDT
      - ALGOUSDC
      - KAIAUSDT
      - NEWTUSDT
      - LPTUSDT
      - PROMUSDT
      - TREETRY
      - ACEUSDT
      - BANANAUSDT
      - LUNCUSDT
      - AWEUSDT
      - 1000SATSUSDT
      - BTCTRY
      - LAUSDT
      - MOVRUSDT
      - KERNELTRY
      - SOLEUR
      - ARBUSDC
      - SOLVUSDT
      - IOTXUSDT
      - BSWUSDT
      - THETRY
      - FLOKIUSDC
      - 1INCHUSDT
      - ATMUSDT
      - SHELLUSDT
      - DOGSUSDT
      - USDTARS
      - VANAUSDT
      - DUSDT
      - ORCATRY
      - ARUSDT
      - SCUSDT
      - AAVEUSDC
      - TAOUSDC
      - JASMYUSDT
      - OMNIUSDC
      - BTCBRL
      - SANDUSDT
      - ETHFITRY
      - SEIUSDC
      - IDEXUSDT
      - NEIROUSDC
      - ADAFDUSD
      - COWUSDT
      - PEPEFDUSD
      - PSGUSDT
      - GMTUSDT
      - TRXUSDC
      - SUIFDUSD
      - VANRYUSDT
      - EPICUSDC
      - HOMEUSDT
      - POLUSDC
      - HIFIUSDT
      - LTOUSDT
      - SSVUSDT
      - UTKUSDT
      - HAEDALUSDT
      - PAXGUSDT
      - STORJUSDT
      - KMDUSDT
      - TFUELUSDT
      - VIRTUALUSDC
      - AIUSDT
      - 1000CHEEMSUSDT
      - PARTIUSDT
      - REDTRY
      - LISTAUSDT
      - BERAUSDT
      - SUPERUSDT
      - GNOUSDT
      - TUTUSDT
      - USTCUSDT
      - THETAUSDT
      - NEARUSDC
      - TRXTRY
      - WUSDT
      - IMXUSDT
      - TONUSDC
      - EGLDUSDT
      - CHZUSDT
      - AXSUSDT
      - FLOKITRY
      - YGGUSDT
      - LQTYUSDT
      - 1000CATUSDT
      - BNBBTC
      - INJUSDC
      - LEVERTRY
      - NEIROTRY
      - IOTAUSDT
      - ROSEUSDT
      - WIFTRY
      - BELUSDT
      - APTUSDC
      - PENDLEUSDC
      - HAEDALUSDC
      - SYRUPTRY
      - QUICKUSDT
      - RUNEUSDC
      - XAIUSDT
      - SUSHIUSDT
      - COOKIEUSDT
      - DOTUSDC
      - XRPJPY
      - KMNOUSDT
      - BAKEUSDT
      - NFPUSDT
      - KNCUSDT
      - ATOMUSDC
      - GRTUSDT
      - LOKAUSDT
      - AXLUSDT
      - FTTUSDT
      - OSMOUSDT
      - NILUSDT
      - MANAUSDT
      - ACTUSDT
      - ZENUSDT
      - WBETHUSDT
      - WLDUSDC
      - NEOUSDT
      - BSWTRY
      - ONEUSDT
      - CYBERUSDT
      - LUMIAUSDT
      - FLUXUSDT
      - TWTUSDT
      - MINAUSDT
      - PNUTTRY
      - CELOUSDT
      - BTCJPY
      - EIGENTRY
      - XVGUSDT
      - MDTUSDT
      - ONDOUSDC
      - PYTHUSDT
      - LEVERUSDT
      - WBTCUSDT
      - PENGUFDUSD
      - METISUSDT
      - SAGAUSDC
      - PERPUSDT
      - BICOUSDT
      - ADXUSDT
      - SKLUSDT
      - COTIUSDT
      - ALPHAUSDT
      - SAHARATRY
      - WINUSDT
      - KSMUSDT
      - MOVEUSDT
      - AEVOUSDT
      - LUNAUSDT
      - SLFUSDT
      - ERAUSDC
      - NXPCUSDC
      - CTRY
      - SANTOSUSDT
      - SHIBUSDC
      - MAGICTRY
      - XNOUSDT
      - KERNELUSDC
      - ACXUSDT
      - CATIUSDT
      - HMSTRUSDT
      - ETHBRL
      - PORTALUSDT
      - FETUSDC
      - GMXUSDT
      - NTRNUSDT
      - CGPTUSDT
      - QIUSDT
      - SUNUSDT
      - WCTUSDC
      - ORDIUSDC
      - TURBOUSDC
      - WAXPUSDT
      - RAYUSDC
      - LAYERUSDT
      - BLURUSDT
      - PIVXUSDT
      - XRPBTC
      - PHBTRY
      - SUSDC
      - TKOUSDT
      - STXUSDT
      - JUPUSDC
      - ENJUSDT
      - TRUMPUSDC
      - PEPEJPY
      - LTCBTC
      - DIAUSDT
      - SUITRY
      - GALAUSDC
      - MASKUSDT
      - TRUUSDT
      - API3USDT
      - BIFIUSDT
      - SOLJPY
      - AVAXTRY
      - REZTRY
      - GNSUSDT
      - RVNUSDT
      - AMPTRY
      - SOLTRY
      - RARETRY
      - FARMUSDT
      - DATAUSDT
      - NEXOUSDT
      - ARDRUSDT
      - YFIUSDT
      - QKCUSDT
      - LTCFDUSD
      - BNBTRY
      - OPUSDC
      - DOGETRY
      - ZKUSDC
      - BCHBTC
      - TLMUSDT
      - ADAEUR
      - ALCXUSDT
      - EURIUSDT
      - MAVTRY
      - ERATRY
      - MBOXUSDT
      - ASTRUSDT
      - IQUSDT
      - ATMTRY
      - PONDUSDT
      - BARUSDT
      - DYMUSDT
      - SHIBTRY
      - TNSRUSDT
      - AUDIOUSDT
      - AUCTIONUSDT
      - MEMETRY
      - CHESSUSDT
      - CAKEUSDC
      - HYPERTRY
      - VELODROMEUSDT
      - C98USDT
      - STOTRY
      - FISUSDT
      - SLPUSDT
      - FILUSDC
      - CUSDC
      - MANTAUSDT
      - FIDAUSDT
      - ORCAUSDC
      - BOMEUSDC
      - AGLDUSDT
      - GUSDT
      - GHSTUSDT
      - PNUTUSDC
      - FLUXUSDC
      - LDOUSDC
      - BBTRY
      - POLYXUSDT
      - ARKMUSDC
      - DASHUSDT
      - WLDTRY
      - QTUMUSDT
      - SCRTUSDT
      - PHAUSDT
      - ANIMEUSDT
      - JUVUSDT
      - ACAUSDT
      - LSKUSDT
      - CITYUSDT
      - SOLETH
      - BNBEUR
      - SEIFDUSD
      - PORTOUSDT
      - IOSTUSDT
      - JOEUSDT
      - INJTRY
      - ARPAUSDT
      - ASRTRY
      - RONINUSDT
      - BCHFDUSD
      - ICPUSDC
      - RSRUSDC
      - VTHOUSDT
      - EUREURI
      - BNTUSDT
      - HOTUSDT
      - GLMUSDT
      - TRXBTC
      - LAZIOUSDT
      - ADATRY
      - USDCPLN
      - USDTDAI
      - CELRUSDT
      - DGBUSDT
      - OGTRY
      - TIAUSDC
      - FDUSDTRY
      - VOXELUSDT
      - LINKBTC
      - BIOUSDC
      - SUIBTC
      - FORTHUSDT
      - GLMRUSDT
      - SYNUSDT
      - RDNTUSDT
      - DOGEEUR
      - ZRXUSDT
      - ZECUSDT
      - BIGTIMEUSDT
      - ACMUSDT
      - CHRUSDT
      - REQUSDT
      - SAHARAUSDC
      - SUIEUR
      - CATITRY
      - BABYTRY
      - DOGEBTC
      - UMATRY
      - USDTCOP
      - SXPUSDT
      - ICXUSDT
      - SFPUSDT
      - IDUSDT
      - EDUUSDT
      - SUIJPY
      - KMNOUSDC
      - BMTTRY
      - LTCEUR
      - RIFUSDT
      - XVSUSDT
      - JSTUSDT
      - LRCUSDT
      - BATUSDT
      - ERAFDUSD
      - THEUSDC
      - BANDUSDT
      - DCRUSDT
      - STRAXUSDT
      - FETTRY
      - PSGTRY
      - DFUSDT
      - DYDXUSDC
      - SCRUSDT
      - BTTCUSDT
      - MLNUSDT
      - BNBETH
      - ZILUSDT
      - HIGHUSDT
      - CETUSUSDC
      - WANUSDT
      - LTCTRY
      - WOOUSDT
      - AVAUSDT
      - INITUSDC
      - SNXUSDT
      - BROCCOLI714USDC
      - REDUSDC
      - RESOLVUSDC
      - ARUSDC
      - EGLDUSDC
      - ANKRUSDT
      - CTSIUSDT
      - EIGENUSDC
      - ONTUSDT
      - HYPERUSDC
      - ENSUSDC
      - DUSKUSDT
      - TIATRY
      - ARBFDUSD
      - DTRY
      - ADAJPY
      - TREEFDUSD
      - ARKMTRY
      - ACHTRY
      - REZUSDC
      - XLMETH
      - VICTRY
      - SYSUSDT
      - DOGEJPY
      - ENAFDUSD
      - FLMUSDT
      - BEAMXTRY
      - DENTUSDT
      - CTKUSDT
      - COSTRY
      - AVAXFDUSD
      - ACETRY
      - LINKBNB
      - TRBUSDC
      - REDFDUSD
      - NKNUSDT
      - IOTRY
      - ETHFIUSDC
      - TURBOTRY
      - ZKFDUSD
      - XRPETH
      - MUBARAKTRY
      - LUNCTRY
      - LDOTRY
      - ATAUSDT
      - 1000CATTRY
      - HIVEUSDT
      - RADUSDT
      - WTRY
      - XRPBRL
      - ARBTRY
      - WLDBTC
      - VANRYTRY
      - STRKUSDC
      - CAKETRY
      - SOLBRL
      - ARKUSDT
      - HUMAUSDC
      - DODOUSDT
      - HBARTRY
      - BOMETRY
      - XLMTRY
      - ALPINEUSDT
      - ILVBTC
      - HBARBTC
      - HMSTRTRY
      - BNSOLUSDT
      - NEXOBTC
      - BONKFDUSD
      - STGUSDT
      - TRXEUR
      - TRUMPTRY
      - PORTALTRY
      - CFXBTC
      - LATRY
      - NEWTTRY
      - RLCUSDT
      - NMRUSDT
      - EURIUSDC
      - CRVTRY
      - HAEDALTRY
      - USD1USDT
      - SIGNUSDC
      - USDTPLN
      - INITTRY
      - JTOUSDC
      - SOLBNB
      - STEEMUSDT
      - ZROUSDC
      - BTCEURI
      - LAUSDC
      - ALTTRY
      - RAREUSDC
      - APTTRY
      - USDTMXN
      - VETUSDC
      - SLFTRY
      - PEPEBRL
      - PYTHUSDC
      - CVCUSDT
      - DOGSTRY
      - RESOLVTRY
      - REIUSDT
      - ACTTRY
      - PUNDIXUSDT
      - GTCUSDT
      - PIXELTRY
      - OPTRY
      - SLPTRY
      - LTCETH
      - MTLUSDT
      - DYMTRY
      - OXTUSDT
      - USDCRON
      - AVAXBTC
      - WBTCBTC
      - USUALUSDC
      - XECUSDT
      - ALTUSDC
      - ONDOTRY
      - APEUSDC
      - GPSTRY
      - FLOWUSDT
      - DYDXTRY
      - SAGATRY
      - KAITOUSDC
      - POLTRY
      - STOUSDC
      - TOWNSFDUSD
      - OMNIBTC
      - TONTRY
      - SXTTRY
      - PENDLETRY
      - SXTUSDC
      - 1000SATSTRY
      - WBETHETH
      - BTCARS
      - POLFDUSD
      - PAXGTRY
      - USUALTRY
      - CAKEBTC
      - THETAUSDC
      - OGNUSDT
      - BELTRY
      - HUMATRY
      - PROVEFDUSD
      - HBARBNB
      - ADABTC
      - XLMEUR
      - ETHEURI
      - MEMEUSDC
      - RPLUSDC
      - 1000CATUSDC
      - SIGNTRY
      - NOTUSDC
      - SOLVTRY
      - BEAMXUSDC
      - COOKIEUSDC
      - AUSDC
      - SOLVFDUSD
      - TUSDT
      - AUDIOTRY
      - PEOPLEUSDC
      - TUSDUSDT
      - KAITOTRY
      - GUNTRY
      - ARPATRY
      - ZKTRY
      - WLDFDUSD
      - NEOUSDC
      - XAITRY
      - AIXBTTRY
      - 1000CHEEMSUSDC
      - BERAUSDC
      - SYNUSDC
      - STRY
      - POWRUSDT
      - TIAFDUSD
      - LINKEUR
      - CKBUSDC
      - RONINTRY
      - XUSDUSDT
      - OPFDUSD
      - USDTZAR
      - LTCBRL
      - BBUSDC
      - SANDFDUSD
      - AITRY
      - BNBJPY
      - ROSETRY
      - VANRYUSDC
      - STXUSDC
      - LINKETH
      - LUNATRY
      - FILFDUSD
      - KMDBTC
      - COTITRY
      - SANTOSTRY
      - ENABTC
      - GALATRY
      - XTZUSDC
      - AAVEBTC
      - DOTFDUSD
      - HMSTRUSDC
      - PEPEEUR
      - PYRBTC
      - IOTAUSDC
      - BARTRY
      - FIDATRY
      - QNTBTC
      - ADXETH
      - USDPUSDT
      - CYBERTRY
      - MUBARAKUSDC
      - SHIBFDUSD
      - SHELLTRY
      - FORMTRY
      - SEITRY
      - WUSDC
      - POLJPY
      - BABYUSDC
      - SANDUSDC
      - CHZUSDC
      - 1000SATSUSDC
      - EIGENFDUSD
      - ALGOTRY
      - IOUSDC
      - JUVTRY
      - XLMBTC
      - HOTTRY
      - DOGSUSDC
      - WIFFDUSD
      - LINKTRY
      - TRXETH
      - OSMOUSDC
      - LISTATRY
      - SOPHTRY
      - AEVOTRY
      - QNTUSDC
      - ZROTRY
      - THETABTC
      - KERNELFDUSD
      - EDUTRY
      - ONETRY
      - PIXELUSDC
      - MBOXTRY
      - GMTTRY
      - BMTUSDC
      - NEWTBNB
      - OMNIFDUSD
      - INITFDUSD
      - NOTTRY
      - CRVBTC
      - ADAETH
      - AIXBTUSDC
      - GRTTRY
      - LDOFDUSD
      - AAVETRY
      - DOTEUR
      - FLOKIFDUSD
      - SOPHUSDC
      - OGBTC
      - TAOBTC
      - EGLDTRY
      - ALPINETRY
      - JUPTRY
      - TRBTRY
      - NEARFDUSD
      - VIRTUALTRY
      - BLURUSDC
      - BANANATRY
      - TONBTC
      - ALICETRY
      - STRKTRY
      - LINKJPY
      - MANTAUSDC
      - MASKTRY
      - DIABTC
      - ARBTUSD
      - BNBBRL
      - HBARFDUSD
      - GPSUSDC
      - USTCTRY
      - XLMJPY
      - AEURUSDT
      - GASTRY
      - HOMEUSDC
      - HOMETRY
      - CHZTRY
      - SUIBNB
      - USDTUAH
      - LAYERTRY
      - NEWTFDUSD
      - BTCZAR
      - UNIFDUSD
      - RENDERTRY
      - SAGABTC
      - DOGEBRL
      - NEIROFDUSD
      - APETRY
      - UNIBTC
      - CETUSTRY
      - ORDITRY
      - HEIUSDC
      - PHBBTC
      - ACTUSDC
      - ETHDAI
      - ADABRL
      - MINATRY
      - ETCBTC
      - TRXXRP
      - PAXGBTC
      - SAGAFDUSD
      - TONFDUSD
      - LTCJPY
      - METRY
      - LRCTRY
      - UNITRY
      - LAFDUSD
      - ONTUSDC
      - PARTITRY
      - CGPTUSDC
      - PYTHTRY
      - XRPBNB
      - ONTTRY
      - TRUMPFDUSD
      - AAVEETH
      - ACATRY
      - ATOMFDUSD
      - MOVETRY
      - STOFDUSD
      - GUNUSDC
      - API3TRY
      - LAYERUSDC
      - API3USDC
      - SFDUSD
      - FETBTC
      - OMBTC
      - KSMTRY
      - SUNTRY
      - INJFDUSD
      - TLMTRY
      - PENDLEBTC
      - BTTCTRY
      - VANATRY
      - CATIUSDC
      - TAOTRY
      - STXBTC
      - ANIMEUSDC
      - BTCPLN
      - JASMYTRY
      - SUPERTRY
      - RAYTRY
      - RENDERFDUSD
      - SANDTRY
      - BNSOLSOL
      - LUMIATRY
      - CVXUSDC
      - ETHFIFDUSD
      - BCHJPY
      - TRXJPY
      - AXSBTC
      - IDEXUSDC
      - ETCUSDC
      - RESOLVFDUSD
      - DYDXFDUSD
      - JTOTRY
      - AXLTRY
      - ETHPLN
      - DOTTRY
      - RVNTRY
      - PEOPLETRY
      - MOVEUSDC
      - AVAXEUR
      - NEOTRY
      - FORMUSDC
      - YGGUSDC
      - LPTTRY
      - ENJTRY
      - MANATRY
      - TFUELBTC
      - NEARBTC
      - ZENUSDC
      - RVNUSDC
      - 1000CATBNB
      - PAXGUSDC
      - FETFDUSD
      - FUNUSDC
      - NEWTUSDC
      - BTCTUSD
      - TRUTRY
      - SHELLUSDC
      - FILTRY
      - MANTATRY
      - ETHTUSD
      - SHIBEUR
      - LAZIOTRY
      - GUNFDUSD
      - GUNBNB
      - ARTRY
      - XECTRY
      - PENDLEFDUSD
      - ARBBTC
      - BTCDAI
      - POLBTC
      - APTFDUSD
      - PHAUSDC
      - BTCMXN
      - WINEUR
      - ATOMTRY
      - POLBRL
      - APTBTC
      - ETCFDUSD
      - BAKETRY
      - WIFBTC
