apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tokio-symbols
  namespace: backend
data:
  symbols-config.yaml: |
    symbols:
    - FLOKIUSDT
    - BONKUSDT
    - ETHUSDT
    - BTCFDUSD
    - BTCUSDT
    - XRPUSDT
    - SOLUSDT
    - ENAUSDT
    - BNBUSDT
    - ETHFDUSD
    - DOGEUSDT
    - DOGEFDUSD
    - SHIBUSDT
    - SOLFDUSD
    - ETHUSDC
    - PENGUUSDT
    - BNBFDUSD
    - SUIUSDT
    - ERAUSDT
    - LTCUSDT
    - HBARUSDT
    - PEPEUSDT
    - USDCUSDT
    - SPKUSDT
    - BTCUSDC
    - XRPUSDC
    - ADAUSDT
    - NEIROUSDT
    - TREEUSDT
    - XRPFDUSD
    - SUIUSDC
    - XLMUSDT
    - ONDOUSDT
    - MEMEUSDT
    - CRVUSDT
    - TONUSDT
    - UNIUSDT
    - SOLUSDC
    - AVAXUSDT
    - ENAUSDC
    - VIRTUALUSDT
    - SEIUSDT
    - LINKUSDT
    - NEARUSDT
    - FDUSDUSDT
    - WIFUSDT
    - AAVEUSDT
    - LINKFDUSD
    - BCHUSDT
    - SCUSDT
    - ORDIUSDT
    - WLDUSDT
    - FORMUSDT
    - SYRUPUSDT
    - BNBUSDC
    - BOMEUSDT
    - PEPEUSDC
    - INITUSDT
    - APTUSDT
    - TRXUSDT
    - PENDLEUSDT
    - CFXUSDT
    - ARBUSDT
    - DOGEUSDC
    - ETHFIUSDT
    - SUSDT
    - TRUMPUSDT
    - PENGUUSDC
    - FDUSDUSDC
    - CAKEUSDT
    - GALAUSDT
    - MKRUSDT
    - ALGOUSDT
    - TAOUSDT
    - ATMUSDT
    - INJUSDT
    - BABYUSDT
    - HBARUSDC
    - A2ZUSDT
    - SAHARAUSDT
    - DOTUSDT
    - IOTXUSDT
    - ETHBTC
    - KAITOUSDT
    - TFUELUSDT
    - USDTTRY
    - PNUTUSDT
    - ETCUSDT
    - FETUSDT
    - RENDERUSDT
    - TREETRY
    - RUNEUSDT
    - LDOUSDT
    - WCTUSDT
    - ICPUSDT
    - TURBOUSDT
    - APEUSDT
    - ADAUSDC
    - DYDXUSDT
    - SPKUSDC
    - OPUSDT
    - PROMUSDT
    - JUPUSDT
    - XTZUSDT
    - BANANAS31USDT
    - PENGUTRY
    - VETUSDT
    - DOGSUSDT
    - 1MBABYDOGEUSDT
    - POLUSDT
    - MUBARAKUSDT
    - ASRUSDT
    - ETHEUR
    - ATOMUSDT
    - ZKUSDT
    - RSRUSDT
    - CKBUSDT
    - SOPHUSDT
    - BTCEUR
    - MEMETRY
    - TIAUSDT
    - TREEUSDC
    - NOTUSDT
    - OMUSDT
    - CVXUSDT
    - USDTBRL
    - CUSDT
    - PIXELUSDT
    - ARKMUSDT
    - NXPCUSDT
    - HYPERUSDT
    - ENSUSDT
    - ALTUSDT
    - AUSDT
    - BONKUSDC
    - SAGAUSDT
    - HEIUSDT
    - PEOPLEUSDT
    - EURUSDC
    - JTOUSDT
    - FILUSDT
    - HUMAUSDT
    - RESOLVUSDT
    - MBLUSDT
    - ENATRY
    - TRBUSDT
    - VANAUSDT
    - QNTUSDT
    - MDTUSDT
    - BELUSDT
    - LPTUSDT
    - BNBBTC
    - COMPUSDT
    - OMNIUSDT
    - EIGENUSDT
    - XRPEUR
    - FUNUSDT
    - CRVUSDC
    - SPKTRY
    - KERNELUSDT
    - BIOUSDT
    - VICUSDT
    - UNIUSDC
    - TUTUSDT
    - ERAUSDC
    - EURUSDT
    - FLOKIUSDC
    - XRPTRY
    - GMTUSDT
    - SOLVUSDT
    - MOVRUSDT
    - ATMTRY
    - THEUSDT
    - MEMEUSDC
    - ETHTRY
    - LINKUSDC
    - RAYUSDT
    - ARBUSDC
    - AIXBTUSDT
    - WIFUSDC
    - LAYERUSDT
    - CETUSUSDT
    - ZROUSDT
    - KMNOUSDT
    - KDAUSDT
    - TSTUSDT
    - SHELLUSDT
    - SAHARATRY
    - LAUSDT
    - KAIAUSDT
    - RENDERUSDC
    - XLMUSDC
    - THETAUSDT
    - CHZUSDT
    - SOLBTC
    - SUPERUSDT
    - BANANAS31USDC
    - SANDUSDT
    - APTUSDC
    - NEIROUSDC
