apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tokio-symbols
  namespace: backend
data:
  symbols-config.yaml: |
    symbols:
    - FLOKIUSDT
    - BONKUSDT
    - ERAUSDT
    - BTCFDUSD
    - ETHUSDT
    - ENAUSDT
    - SOLUSDT
    - BTCUSDT
    - XRPUSDT
    - PENGUUSDT
    - BNBUSDT
    - ETHFDUSD
    - DOGEUSDT
    - DOGEFDUSD
    - SOLFDUSD
    - ETHUSDC
    - BNBFDUSD
    - SHIBUSDT
    - SPKUSDT
    - SUIUSDT
    - HBARUSDT
    - LTCUSDT
    - CRVUSDT
    - PEPEUSDT
    - USDCUSDT
    - CFXUSDT
    - NEIROUSDT
    - TREEUSDT
    - ADAUSDT
    - UNIUSDT
    - SUIUSDC
    - XRPFDUSD
    - XRPUSDC
    - XLMUSDT
    - ENAUSDC
    - BCHUSDT
    - BTCUSDC
    - A2ZUSDT
    - TONUSDT
    - AVAXUSDT
    - SUSDT
    - WIFUSDT
    - VIRTUALUSDT
    - ONDOUSDT
    - SEIUSDT
    - PENGUUSDC
    - AAVEUSDT
    - NEARUSDT
    - SOLUSDC
    - LINKUSDT
    - SOPHUSDT
    - ORDIUSDT
    - SYRUPUSDT
    - WLDUSDT
    - FDUSDUSDT
    - KERNELUSDT
    - FORMUSDT
    - BANANAS31USDT
    - IOTXUSDT
    - APTUSDT
    - TRXUSDT
    - ETHFIUSDT
    - PNUTUSDT
    - LINKFDUSD
    - PEPEUSDC
    - INITUSDT
    - ALGOUSDT
    - VICUSDT
    - DOGEUSDC
    - CAKEUSDT
    - HBARUSDC
    - BNBUSDC
    - PENDLEUSDT
    - ERAUSDC
    - QKCUSDT
    - BIOUSDT
    - MDTUSDT
    - INJUSDT
    - GALAUSDT
    - BABYUSDT
    - TAOUSDT
    - PENGUTRY
    - ARBUSDT
    - TURBOUSDT
    - TRUMPUSDT
    - BOMEUSDT
    - ASRUSDT
    - ATMUSDT
    - MKRUSDT
    - MEMEUSDT
    - LDOUSDT
    - CVXUSDT
    - FDUSDUSDC
    - SPKUSDC
    - FETUSDT
    - USDTTRY
    - ADAUSDC
    - ETHBTC
    - ICPUSDT
    - DOTUSDT
    - OPUSDT
    - JUPUSDT
    - ACMUSDT
    - RENDERUSDT
    - BONKUSDC
    - SCUSDT
    - MUBARAKUSDT
    - APEUSDT
    - ENATRY
    - TREETRY
    - OMNIUSDT
    - PROMUSDT
    - CUSDT
    - ZKUSDT
    - ETCUSDT
    - CRVUSDC
    - VETUSDT
    - RUNEUSDT
    - 1MBABYDOGEUSDT
    - RESOLVUSDT
    - CYBERUSDT
    - OMUSDT
    - TFUELUSDT
    - TIAUSDT
    - SPKTRY
    - CFXUSDC
    - DOGSUSDT
    - DYDXUSDT
    - USDTBRL
    - XTZUSDT
    - ETHEUR
    - SAHARAUSDT
    - HYPERUSDT
    - BANANAS31USDC
    - HOMEUSDT
    - NOTUSDT
    - KAITOUSDT
    - CKBUSDT
    - HUMAUSDT
    - ALTUSDT
    - ATOMUSDT
    - ENSUSDT
    - UNIUSDC
    - JTOUSDT
    - MAVUSDT
    - EURUSDC
    - POLUSDT
    - RPLUSDT
    - SAGAUSDT
    - FLOKIUSDC
