apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tokio-binance-mock-symbols
  namespace: backend
data:
  symbols-config.yaml: |
    symbols:
      - FLOKIUSDT
      - BONKUSDT
      - ETHUSDT
      - XRPUSDT
      - SOLUSDT
      - BTCFDUSD
      - BTCUSDT
      - DOGEUSDT
      - SHIBUSDT
      - NEIROUSDT
      - BNBUSDT
      - ETHFDUSD
      - PENGUUSDT
      - DOGEFDUSD
      - PEPEUSDT
      - SOLFDUSD
      - CRVUSDT
      - XLMUSDT
      - XRPUSDC
      - SUIUSDT
      - ADAUSDT
      - ETHUSDC
      - HBARUSDT
      - BOMEUSDT
      - ENAUSDT
      - XRPFDUSD
      - PEPEUSDC
      - BNBFDUSD
      - LTCUSDT
      - VIRTUALUSDT
      - USDCUSDT
      - UNIUSDT
      - HAEDALUSDT
      - WIFUSDT
      - PNUTUSDT
      - BTCUSDC
      - SEIUSDT
      - SUIUSDC
      - TRUMPUSDT
      - ONDOUSDT
      - AAVEUSDT
      - FLOKIUSDC
      - NEARUSDT
      - ALGOUSDT
      - LINKFDUSD
      - ETHFIUSDT
      - FDUSDUSDT
      - KAITOUSDT
      - AVAXUSDT
      - SYRUPUSDT
