apiVersion: v1
kind: ConfigMap
metadata:
  name: config-flink-pipeline
  namespace: backend
data:
  flink-pipeline.yaml: |
    source:
      depthupdate:
        parallelism: 1
        sharing-group: "default"
      snapshot:
        parallelism: 1
        sharing-group: "default"
    orderbook:
      parallelism: 2
      sharing-group: "orderbook-group"
    metrics:
      extraction1:
        parallelism: 1
        sharing-group: "default"
      extraction2:
        parallelism: 1
        sharing-group: "default"
      extraction3:
        parallelism: 1
        sharing-group: "default"
    sink:
      parallelism: 3
      sharing-group: "sink-group"
