apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tokio-symbols
  namespace: backend
data:
  symbols-config.yaml: |
    symbols:
      - BTC-USDT
      - ETH-USDT
      - SOL-USDT
      - XRP-USDT
      - BTC-USDC
      - LTC-USDT
      - ETH-USDC
      - SUI-USDT
      - USDC-USDT
      - ZEC-USDT
      - BNB-USDT
      - DOGE-USDT
      - PAXG-USDT
      - TON-USDT
      - ADA-USDT
      - TAO-USDT
      - PEPE-USDT
      - ENSO-USDT
      - ROSE-USDT
      - DASH-USDT
      - LINK-USDT
      - TRX-USDT
      - SOMI-USDT
      - NEAR-USDT
      - ZKC-USDT
      - SOL-USDC
      - AVAX-USDT
      - LINEA-USDT
      - FF-USDT
      - WLFI-USDT
      - PUMP-USDT
      - UNI-USDT
      - XRP-USDC
      - SHIB-USDT
      - AVNT-USDT
      - ATA-USDT
      - USD1-USDT
      - ZRO-USDT
      - ASTER-USDT
      - PENGU-USDT
      - ONDO-USDT
      - XLM-USDT
      - HBAR-USDT
      - WIF-USDT
      - WCT-USDT
      - DOT-USDT
      - ARB-USDT
      - TURTLE-USDT
      - XPL-USDT
      - TRUMP-USDT
      - APT-USDT
      - ENA-USDT
      - KAIA-USDT
      - FET-USDT
      - BCH-USDT
      - AAVE-USDT
      - AXS-USDT
      - 2Z-USDT
      - AUCTION-USDT
      - ICP-USDT
      - USDT-BRL
      - FIL-USDT
      - LPT-USDT
      - STRK-USDT
      - STO-USDT
      - RENDER-USDT
      - BANANA-USDT
      - ATOM-USDT
      - FUN-USDT
      - SEI-USDT
      - POL-USDT
      - VIRTUAL-USDT
      - TIA-USDT
      - BB-USDT
      - ZEN-USDT
      - PYTH-USDT
      - ZBT-USDT
      - MIRA-USDT
      - BONK-USDT
      - CRV-USDT
      - WLD-USDT
      - SAND-USDT
      - PROVE-USDT
      - DUSK-USDT
      - CHZ-USDT
      - ZK-USDT
      - ALGO-USDT
      - NOM-USDT
      - OP-USDT
      - RESOLV-USDT
      - PLUME-USDT
      - GPS-USDT
      - LTC-USDC
      - FLOKI-USDT
      - MINA-USDT
      - SYRUP-USDT
      - S-USDT
      - HFT-USDT
      - PENDLE-USDT
      - INJ-USDT
      - VANA-USDT
      - JUP-USDT
      - NOT-USDT
      - EUL-USDT
      - IO-USDT
      - ZIL-USDT
      - W-USDT
      - AIXBT-USDT
      - USDT-DAI
      - TREE-USDT
      - RUNE-USDT
      - ADA-USDC
      - RAY-USDT
      - AR-USDT
      - CFX-USDT
      - VET-USDT
      - QNT-USDT
      - WAL-USDT
      - LDO-USDT
      - JASMY-USDT
      - AGLD-USDT
      - SCRT-USDT
      - HOLO-USDT
      - HYPER-USDT
      - ETHFI-USDT
      - STG-USDT
      - ARKM-USDT
      - DOGE-USDC
      - F-USDT
      - SHELL-USDT
      - SXT-USDT
      - 0G-USDT
      - ANIME-USDT
      - NEWT-USDT
      - INIT-USDT
      - MOVE-USDT
      - A-USDT
      - OPEN-USDT
      - ORDI-USDT
      - SUPER-USDT
      - RSR-USDT
      - KAITO-USDT
      - APE-USDT
      - TRB-USDT
      - STX-USDT
      - BOME-USDT
      - EIGEN-USDT
      - ZKP-USDT
      - BREV-USDT
      - MET-USDT
      - BERA-USDT
      - GIGGLE-USDT
      - NEO-USDT
      - KITE-USDT
      - ETH-DAI
      - ASTR-USDT
      - BTC-EUR
      - TURBO-USDT
      - MBL-USDT
      - HAEDAL-USDT
      - ETC-USDT
      - SAHARA-USDT
      - CAKE-USDT
      - SOPH-USDT
      - CVX-USDT
      - SKY-USDT
      - NMR-USDT
      - LUNC-USDT
      - SPK-USDT
      - MANA-USDT
      - ERA-USDT
      - YGG-USDT
      - CKB-USDT
      - BIO-USDT
      - SSV-USDT
      - A2Z-USDT
      - DOGS-USDT
      - SOLV-USDT
      - FTT-USDT
      - COTI-USDT
      - KNC-USDT
      - METIS-USDT
      - PNUT-USDT
      - THETA-USDT
      - CYBER-USDT
      - OM-USDT
      - DODO-USDT
      - BNB-USDC
      - SKL-USDT
      - XTZ-USDT
      - G-USDT
      - DOT-USDC
      - LUNA-USDT
      - ETH-EUR
      - SOL-USD1
      - FLUX-USDT
      - ETH-USD1
      - VANRY-USDT
      - HMSTR-USDT
      - DYDX-USDT
      - PORTAL-USDT
      - GUN-USDT
      - REZ-USDT
      - ENJ-USDT
      - BAT-USDT
      - BMT-USDT
      - ORCA-USDT
      - BTC-USD1
      - D-USDT
      - JST-USDT
      - LINK-USDC
      - WAN-USDT
      - NTRN-USDT
      - EGLD-USDT
      - BTC-BRL
      - SAPIEN-USDT
      - MANTA-USDT
      - ACH-USDT
      - DATA-USDT
      - HUMA-USDT
      - SFP-USDT
      - ALLO-USDT
      - USUAL-USDT
      - AEVO-USDT
      - TWT-USDT
      - ENS-USDT
      - PHA-USDT
      - MUBARAK-USDT
      - KERNEL-USDT
      - JTO-USDT
      - WLFI-USD1
      - TRX-USDC
      - MOVR-USDT
      - COMP-USDT
      - SUI-USDC
      - IMX-USDT
      - BIGTIME-USDT
      - ONE-USDT
      - STRAX-USDT
      - IOTA-USDT
      - DCR-USDT
      - WIN-USDT
      - BCH-USDC
      - YFI-USDT
      - LA-USDT
      - ARPA-USDT
      - API3-USDT
      - ADX-USDT
      - KMNO-USDT
      - FET-USDC
      - EDEN-USDT
      - ILV-USDT
      - USTC-USDT
      - C-USDT
      - ZRX-USDT
      - TNSR-USDT
      - BARD-USDT
      - SCR-USDT
      - ONT-USDT
      - BTC-DAI
      - NXPC-USDT
      - PARTI-USDT
      - XRP-USD1
      - XLM-USDC
      - SUSHI-USDT
      - ME-USDT
      - GMT-USDT
      - MORPHO-USDT
      - TAO-USDC
      - DGB-USDT
      - STORJ-USDT
      - 1INCH-USDT
      - PROM-USDT
      - XNO-USDT
      - WOO-USDT
      - XAI-USDT
      - SXP-USDT
      - SLP-USDT
      - WBTC-USDT
      - IOTX-USDT
      - UMA-USDT
      - OXT-USDT
      - BLUR-USDT
      - MAGIC-USDT
      - MASK-USDT
      - SNX-USDT
      - HOME-USDT
      - AVA-USDT
      - ETH-BRL
      - AVAX-USDC
      - MMT-USDT
      - TOWNS-USDT
      - NIL-USDT
      - CELO-USDT
      - FORTH-USDT
      - OSMO-USDT
      - TRU-USDT
      - ALICE-USDT
      - CATI-USDT
      - KSM-USDT
      - GRT-USDT
      - TUT-USDT
      - SIGN-USDT
      - KAVA-USDT
      - CGPT-USDT
      - TFUEL-USDT
      - MEME-USDT
      - PYR-USDT
      - ICX-USDT
      - CETUS-USDT
      - ADA-USD1
      - BAND-USDT
      - HBAR-USDC
      - NEAR-USDC
      - XEC-USDT
      - MAV-USDT
      - COOKIE-USDT
      - EDU-USDT
      - LAYER-USDT
      - EPIC-USDT
      - CELR-USDT
      - PIXEL-USDT
      - WIN-TRX
      - ANKR-USDT
      - LISTA-USDT
      - YB-USDT
      - COW-USDT
      - RONIN-USDT
      - AWE-USDT
      - LSK-USDT
      - DOLO-USDT
      - C98-USDT
      - GLM-USDT
      - VTHO-USDT
      - TLM-USDT
      - ENA-USDC
      - TON-USDC
      - FLOW-USDT
      - TRUMP-USDC
      - GAS-USDT
      - NEIRO-USDT
      - GMX-USDT
      - SHIB-USDC
      - AMP-USDT
      - HIGH-USDT
      - DYM-USDT
      - PEPE-USDC
      - PEOPLE-USDT
      - BABY-USDT
      - DIA-USDT
      - RPL-USDT
      - DOGE-USD1
      - GLMR-USDT
      - CHR-USDT
      - RVN-USDT
      - ATOM-USDC
      - RLC-USDT
      - DENT-USDT
      - DEXE-USDT
      - GTC-USDT
      - LUMIA-USDT
      - SUN-USDT
      - ALPINE-USDT
      - DEGO-USDT
      - GNS-USDT
      - QI-USDT
      - S-USDC
      - REQ-USDT
      - A-USDC
      - BICO-USDT
      - RDNT-USDT
      - LQTY-USDT
      - NKN-USDT
      - WIF-USDC
      - LRC-USDT
      - AUDIO-USDT
      - FLUX-USDC
      - OGN-USDT
      - PUNDIX-USDT
      - CTSI-USDT
      - SYS-USDT
      - CVC-USDT
      - T-USDT
      - POLYX-USDT
      - SYN-USDT
      - ACX-USDT
      - ALGO-USDC
      - ID-USDT
      - INJ-USDC
      - IOST-USDT
      - JUP-USDC
      - FIDA-USDT
      - OP-USDC
      - HEI-USDT
      - ONDO-USDC
      - TUSD-USDT
      - POND-USDT
      - QTUM-USDT
      - MTL-USDT
      - QUICK-USDT
      - USDP-USDT
      - ETC-USDC
      - APE-USDC
      - SHIB-DOGE
      - LUNC-USDC
      - RUNE-USDC
      - FLOKI-USDC
      - LDO-USDC
      - NFP-USDT
      - USDE-USDT
      - LUNA-USDC
      - DASH-ETH
      - QKC-USDT
      - XRP-ETH
      - GMT-USDC
      - LTC-ETH
      - TRX-ETH
      - ETH-BTC
      - ATOM-ETH
      - LTC-BTC
      - XLM-ETH
      - ZEC-BTC
      - XRP-BTC
      - VET-ETH
      - MANA-ETH
      - PAXG-BTC
      - ATOM-BTC
      - WBTC-BTC
      - TRX-BTC
      - ETC-ETH
      - XLM-BTC
      - DOGE-BTC
      - ZIL-ETH
      - DASH-BTC
      - ADA-BTC
      - BNB-BTC
      - DOT-BTC
      - ONT-BTC
      - SCRT-BTC
      - FET-BTC
      - BCH-BTC
      - STX-BTC
      - LINK-BTC
      - CHZ-BTC
      - IOTX-ETH
      - WAN-BTC
      - HBAR-BTC
      - NEAR-BTC
      - COTI-BTC
      - AVA-BTC
      - ETC-BTC
      - AAVE-BTC
      - AR-BTC
      - AVAX-BTC
      - ICP-BTC
      - VET-BTC
      - EGLD-BTC
      - NEO-BTC
      - ALGO-BTC
      - RUNE-BTC
      - RLC-BTC
      - OGN-BTC
      - XTZ-BTC
      - SNX-BTC
      - A-BTC
      - KNC-BTC
      - IOTA-BTC
      - INJ-BTC
