apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: binance-depthupdate-raw
  namespace: backend
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  topicName: binance-depthUpdate-raw
  partitions: 1
  replicas: 1
  config:
    retention.minutes: 15
    retention.bytes: -1
    flush.offset.checkpoint.interval.ms: 0
    cleanup.policy: "delete"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: binance-microstructure-raw
  namespace: backend
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  topicName: binance-microstructure-raw
  partitions: 5
  replicas: 1
  config:
    retention.minutes: 45
    retention.bytes: -1
    flush.offset.checkpoint.interval.ms: 1000
    cleanup.policy: "delete"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: schemas
  namespace: backend
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  topicName: _schemas
  partitions: 1
  replicas: 1
  config:
    cleanup.policy: "compact"
    retention.ms: -1
